### ISSUE TITLE
TupleQueryResultView does not report back errors

### ISSUE THREAD

**Issue by pulquero** [eclipse/rdf4j#4512] opened 2023-04-17 15:51 UTC
### Current Behavior

If a QueryEvaluationException occurs, RDF4J server still sends a HTTP 200 code.

### Expected Behavior

RDF4J server should send 500.

### Version

4.2.3

### Are you interested in contributing a solution yourself?

None

### Anything else?

TupleQueryResultView does have the correct error handling code
```
			} catch (QueryEvaluationException e) {
				logger.error("Query evaluation error", e);
				response.sendError(SC_INTERNAL_SERVER_ERROR, "Query evaluation error: " + e.getMessage());
```
Unfortunately it has an "auto-close" try not a standard try, so the output is sent 200 regardless. This
```
try (OutputStream out = response.getOutputStream()) {
```
should be something like
```
try {
OutputStream out = response.getOutputStream();
.
.
.
out.close();
```
Note out.close() is purposely not in a finally block, so it only commits the response on success.

**Comment by pulquero** [comment] 2023-04-17 19:55
Here's the commit that broke it:
https://github.com/eclipse/rdf4j/commit/217be508c4e7485dad7062516ad7d819b0e57aed#

**Comment by pulquero** [comment] 2023-04-17 19:59
Or can use an autoclose-try, but need to have a separate nested try..catch inside it.

**Comment by abrokenjester** [comment] 2023-04-22 02:51
I agree there is a problem here with response statuses, but I think this might be an issue that was even there before the refactor you mention, and therefore not related to the introduction of the try-with-resources. 

The root of the problem seems to me to be that in the error handling, we are trying to change the response status code from 200 to 500, but this happens after the response has already been committed (i.e. data has already started being sent to the client).

In any case, I am having some trouble coming up with a quick test that reproduces the problem - this might be easier to tackle in the develop branch where we've got some better testing library support for things related to HTTP client/server interactions.

**Comment by abrokenjester** [comment] 2023-04-29 00:53
I cannot actually reproduce the issue. I've added some additional test coverage but everything indicates this works as expected.

**Comment by pulquero** [comment] 2023-04-30 21:48
I get correct behaviour if an exception occurs during DefaultQueryRequestHandler.evaluateQuery(). But not if the exception occurs during QueryResults.report() in TupleQueryResultView.

**Comment by abrokenjester** [comment] 2023-04-30 22:50
> I get correct behaviour if an exception occurs during DefaultQueryRequestHandler.evaluateQuery(). But not if the exception occurs during QueryResults.report() in TupleQueryResultView.

Ah. Yes, I think this may be because once `QueryResults.report()` starts working, it starts streaming content to the response outputstream. As soon as that happens, the response is "committed" (that is, it starts actually sending data to the client) and the status code can no longer be changed. So I don't think this is related to the `try-with-resources`, but just due to the fact that we designed this endpoint to directly stream the result to the response outputstream _while_ we're evaluating. 

Unfortunately the only way around this that I can see is that we buffer the entire query result server side, before streaming the response. I'm not sure that is a fix we want to do though as it introduces all sorts of scalability / memory pressure issues with answering queries.

**Comment by pulquero** [comment] 2023-05-01 12:38
The servlet api says "Calling flush() on the ServletOutputStream commits the response." I'm pretty sure in the past, I've been able to call sendError and it'll discard any output written, because it does some buffering. I'm pretty sure it doesn't send everything chunk encoded, so it would need to buffer to set the content length header.

In my particular case, the exception occurs after getting the output stream but before anything is written. The current behaviour results in a 200, content-length: 0

**Comment by abrokenjester** [comment] 2023-05-01 23:44
Could you provide a reproducible example somehow?

**Comment by pulquero** [comment] 2023-05-18 15:22
Here is the stack trace. If you attach a debugger and throw an exception at this line
`
	at org.eclipse.rdf4j.query.QueryResults.report(QueryResults.java:301)
	at org.eclipse.rdf4j.http.server.repository.TupleQueryResultView.renderInternal(TupleQueryResultView.java:102)
	at org.eclipse.rdf4j.http.server.repository.QueryResultView.render(QueryResultView.java:66)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1405)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1149)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1088)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at com.github.ziplet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:263)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

**Comment by pulquero** [comment] 2023-05-18 20:46
Stepping, I get the following code path:
QueryResults:298 (autoclose on the try - TupleQueryResult closed)
TupleQueryResultView:78 (autoclose on the try - response committed)
TupleQueryResultView:106-108 (catch clause - attempt to set response code after commit)
Empty 200 response in the REST client.

**Comment by abrokenjester** [comment] 2023-06-22 23:12
Ah, thanks, yes, I see the problem now. I don't think I had realized that a try-with-resources calls close _before_ it handles the catch (I somehow had it in my had that it's syntactic sugar for a finally clause).

**Closed** 2023-06-25 05:10 UTC
Labels: 🐞 bug, 📦 server

**Comment by pulquero** [comment] 2023-07-07 15:35
I've upgraded to 4.3.3 and can confirm we are now seeing 500 code + error messages! Thanks!
