### ISSUE TITLE
Repositories.tupleQuery uses unnecessary open/commit/rollback and fails with Virtuoso

### ISSUE THREAD

**Issue by tfrancart** [eclipse/rdf4j#829] opened 2017-05-22 07:54 UTC
Using Repositories.tupleQuery eventually executes the query in Repositories.get. This method calls connection.open() and connection.commit().

1. Calling connection.open() and connection.commit() is unnecessary for read-only TupleQueries (?)
1. Read-only Virtuoso SPARQL endpoints return an exception when the commit() method is called.

It would be better if Repositories.tupleQuery() executes the query without commiting the connection.

**Comment by barthanssens** [comment] 2017-05-22 14:28
Seems to be related to (or duplicate of ?) https://github.com/eclipse/rdf4j/issues/93

**Comment by tfrancart** [comment] 2017-05-22 14:29
Exactly a duplicate of #93 ! Thanks for pointing out. Feel free to close the issue if you wish.

**Comment by barthanssens** [comment] 2017-05-22 14:35
I don't have the necessary rights to close the issue, but I think you can close your ticket yourself (or ask @jeenbroekstra to close it for you)

**Closed** 2017-05-22 14:39 UTC
