### ISSUE TITLE
SHACL Validation report swalled by HTTP Repository

### ISSUE THREAD

**Issue by vincentmigot** [eclipse/rdf4j#2082] opened 2020-04-09 00:50 UTC
Hello and thanks for your work !

I try to use SHACL in my software for data validation and it seems very promising, but not really ready for production ;)

When I get a SHACL validation failed exception with HTTP Repository I only get the following generic response, with no possibilities to get more informations:

org.eclipse.rdf4j.repository.RepositoryException: org.eclipse.rdf4j.sail.shacl.ShaclSailValidationException: Failed SHACL validation

I use the code snippet pointed in your [documentation](https://rdf4j.org/documentation/programming/shacl/#validation-results) and it works great with a InMemoryRepository but not with HTTP Repository (I haven't try with other types of repository).

I think that's because validation report is in the "cause" part of the initial repository exception and is lost during the serialization process to produce response message in RDF4J Server.

Is it possible to do something about that ?

If it is, I will be pleased to contribute if you point me in a direction to look into the code base.

Thanks

**Comment by jeenbroekstra** [comment] 2020-04-09 03:14
You'll be pleased to know that your issue is a duplicate of #1900, which was recently fixed and will be included in the 3.2 release. In fact, the first milestone build (3.2.0-M1) should have that improvement available already. Give it a spin, and let us know if it works.

**Closed by jeenbroekstra** 2020-04-09 03:14 UTC
Labels: duplicate
