### ISSUE TITLE
Problem using SPARQLRepository to query Blazegraph endpoint

### ISSUE THREAD

**Issue by lindamthomas07** [eclipse/rdf4j#1393] opened 2019-04-16 06:59 UTC
For Eclipse RDF4j with version above 2.2 , queries are not returning any results. If there is a time delay between the executions (Debug mode execution) of RDF4j statements, then query results are returned. Otherwise No.

**Comment by barthanssens** [comment] 2019-04-16 08:32
Hi,

Could you please provide a little more information, thanks.

- E.g is it still an issue with  2.4.6 or 2.5.1 ?
- Are you using an embedded NativeStore / MemStore, or a client-server setup with e.g. RDF4J server or OntoText GraphDB ?
- Could you provide an example query and/or a code snippet ?

**Comment by lindamthomas07** [comment] 2019-04-16 08:48
-  Issue exists while upgrading from 2.2 to version 2.3.2 or above
- Blazegraph is deployed in an external server and we are using SPARQL Repository connection to access it
-Below is a sample query to fetch all projects for a user
  `prefix projects: <http://www.sample.com/test/projects/> 
    prefix users:<http://www.sample.com/test/users/>
   SELECT DISTINCT ?projects 	
 	WHERE{ 		?a projects:hasName ?projects ;  	
	   projects:hasUser users:1234 . 	
}
`

**Comment by barthanssens** [comment] 2019-04-17 14:23
Thanks, is it Blazegraph 2.1.5 (which was released fairly recently) or the older version 2.1.4 ?

(I don't think that will make much difference, since they both seem to be using a very old Sesame 2.7 version, but one never knows...)

**Comment by lindamthomas07** [comment] 2019-04-22 05:51
What is the resolution for the above issue

**Comment by jeenbroekstra** [comment] 2019-05-31 06:40
I'm not sure I understand what the actual issue is. Let me try and summarize: you use an Rdf4j SPARQLRepository to access a remote Blazegraph server and query it. If you use rdf4j 2.2, this works as expected. However, if you use rdf4j 2.3 or newer, this does not work. Did I understand that correctly? 

What exactly are you seeing when it doesn't work as expected? Do you get an empty result? Does the query time out? Do you see any error messages, or anything in the rdf4j logs or in the Blazegraph server logs? Is this only for a specific query (do some queries work, and some queries not)?

**Comment by jeenbroekstra** [comment] 2019-06-01 04:33
I have ran a local blazegraph server (2.1.5) and have tried to query it through a SPARQLRepository (rdf4j 2.5.2). This worked as expected. The only thing I can think of is a syntax error in the data response that Blazegraph sends back (since rdf4j 2.2 our parsers have become better at detecting syntax errors). If that is the case, though, there should be an error to indicate this in the rdf4j logs.  Fixing it will involve configuring the Rio parser to be more forgiving.

**Comment by lindamthomas07** [comment] 2019-06-26 09:47
I'm still facing this issue. Debugged into RDF4j framework code. Finally found out the piece of code which is causing the issue.


`package org.eclipse.rdf4j.http.client;
private void autoCloseRunnable(QueryResult<?> result, Runnable runner) {
		synchronized (executing) {
			executing.add(result);
		}
		executor.execute(() -> {
			try {
				runner.run();
			} finally {
				synchronized (executing) {
					executing.remove(result);
				}
			}
		});
	}`

If there is a little time delay in execution of these lines, results are parsed correctly. otherwise it simply returns an empty array. Its surprising to see such an issue. All this time I thought blazegraph is not returning the results. But it is the parsing that is causing the issue!

Please fix it and let us know.

**Comment by jeenbroekstra** [comment] 2019-06-26 22:32
@lindamthomas07 the code you quoted is the part of the `BackgroundResultExecutor`, which executes processing of the server's query result in a separate thread. While it's possible there is a timing issue in play here, I'm having a hard time seeing it, or reproducing the problem.

Can you construct a minimal working example that demonstrates the problem and post/attach it here? If possible this example should include a sample of the data you're trying to query, the query you're trying to execute, and the actual code you use to run the query and process its result.

**Comment by jeenbroekstra** [comment] 2019-07-16 10:41
Closing for now as this is not reproducible with the available information. If you can provide additional details so that we can reproduce the problem we can re-open.

**Closed by jeenbroekstra** 2019-07-16 10:41 UTC
Labels: cannot reproduce
