### ISSUE TITLE
Workbench cannot properly open newly created repository [Google Chrome]

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#640] opened 2016-11-02 22:10 UTC
In Google Chrome, when creating a new repository in the RDF4J Workbench, for some reason the repository menu options remain "grayed out". Even selecting a different repo and then re-selecting the new one does not help. It appears either a browser cache refresh or a tomcat restart does help though. See screenshot.

![screen shot 2016-11-03 at 09 06 29](https://cloud.githubusercontent.com/assets/728776/19949274/d7ca2ffa-a1a4-11e6-86cd-c7938640306a.png)

Issue appears to be specific to Google Chrome: both Firefox and Apple Safari do not show this behavior. 

Chrome console log reports the following upon creating the new repository:

![screen shot 2016-11-03 at 09 15 39](https://cloud.githubusercontent.com/assets/728776/19949534/507bf392-a1a6-11e6-89f8-fc68b66f2a35.png)

Originally reported on the rdf4j-user group: https://groups.google.com/d/msg/rdf4j-users/-qRhXnMvjyM/PGMDTpbdAwAJ

**Comment by jamesrdf** [comment] 2017-04-12 17:20
This is a duplicate of #141

**Closed** 2017-05-24 15:03 UTC
Labels: bug
