### ISSUE TITLE
SYSTEM repository is not crash proof

### ISSUE THREAD

**Issue by nikolavp** [eclipse/rdf4j#645] opened 2016-11-09 15:33 UTC
Creating a repository through the API and then crashing the process with kill -9 doesn't save the newly created repository in SYSTEM.

It seems that there is a method called sync which is called on graceful shutdown but this is not called on system crash of any sort

**Comment by jeenbroekstra** [comment] 2016-11-09 21:33
Isn't this a duplicate of #623 ? If so this was fixed in 2.1.1.

**Comment by jeenbroekstra** [comment] 2016-11-09 23:21
Btw the memory store is indeed not 100% guaranteed crash proof - if a crash happens _during_ `sync` it is still likely to become corrupted. That is a known consequence of the memory store's persistence design, but not considered a bug. 

I think your specific scenario may have been fixed by #623 but if you want the system repo to have more general durability, we should perhaps consider switching its backend to a native store. That will require some significant changes though, specifically because we'll need migration code to update existing deployments in a secure fashion.

**Closed** 2016-11-14 21:30 UTC
Labels: duplicate
