### ISSUE TITLE
NPE on SPARQL Update parsing

### ISSUE THREAD

**Issue by knoan** [eclipse/rdf4j#2071] opened 2020-04-04 17:41 UTC
**Environment**

rdf4j: 3.1.2

**How to reproduce**

```java
org.eclipse.rdf4j.query.parser.QueryParserUtil.parseUpdate(QueryLanguage.SPARQL,

   "clear all; insert { ?s ?p ?o  } where { service <http://exmple.org/> { ?s ?p ?o  } }",

   null

);
```

**Expected behaviour**

SPARQL Update is parsed.

**Actual behaviour**

```
Exception in thread "main" java.lang.NullPointerException
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTServiceGraphPattern.getPatternString(ASTServiceGraphPattern.java:71)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:1055)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTServiceGraphPattern.jjtAccept(ASTServiceGraphPattern.java:43)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:1022)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTGraphPatternGroup.jjtAccept(ASTGraphPatternGroup.java:24)
	at org.eclipse.rdf4j.query.parser.sparql.ast.SimpleNode.childrenAccept(SimpleNode.java:152)
	at org.eclipse.rdf4j.query.parser.sparql.AbstractASTVisitor.visit(AbstractASTVisitor.java:730)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTWhereClause.jjtAccept(ASTWhereClause.java:24)
	at org.eclipse.rdf4j.query.parser.sparql.UpdateExprBuilder.visit(UpdateExprBuilder.java:291)
	at org.eclipse.rdf4j.query.parser.sparql.UpdateExprBuilder.visit(UpdateExprBuilder.java:61)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTModify.jjtAccept(ASTModify.java:25)
	at org.eclipse.rdf4j.query.parser.sparql.SPARQLParser.parseUpdate(SPARQLParser.java:118)
	at org.eclipse.rdf4j.query.parser.QueryParserUtil.parseUpdate(QueryParserUtil.java:76)
	…
```

**Notes**

- the exception is thrown only if both update operations are included in the same source string and the update with the nested SERVICE clause is the second one
- the first update operation seems to be immaterial
- the issue seems specific of the nested SERVICE clause; parses correctly if replacing it with another nested construct like SELECT

**Comment by jeenbroekstra** [comment] 2020-04-05 23:15
This is a duplicate of #2013. There's a fix available in 3.1.3 nightly snapshot, we'll probably do a patch release soon.

**Closed by jeenbroekstra** 2020-04-05 23:15 UTC
Labels: duplicate
