### ISSUE TITLE
SimpleLiteral hashCode should ignore case for language tags

### ISSUE THREAD

**Issue by nikolavp** [eclipse/rdf4j#665] opened 2016-11-23 16:04 UTC
The contract for equals and hashcode is now broken for the following literals

```java
final SimpleValueFactory vf = SimpleValueFactory.getInstance();
Literal v1 = vf.createLiteral("test", "EN");
Literal v2 = vf.createLiteral("test", "en");
v1.equals(v2) // true
v1.hashCode() == v2.hashCode() // false
```
this is caused because equals is using ignore case but the hashcode doesn't. Please lowercase the literal 's language in the setLanguage method.

**Comment by ansell** [comment] 2016-11-23 19:48
+1, since we moved to the new hashCode implementation including the language field, it needs to take it into account equivalently for hashCode. The alternatives if the performance hit to using equalsIgnoreCase for hashCode are caching the calculated hashCode or taking language out of the hashCode again.

Lowercasing the literal's language has been discussed in the past, but my recollection was there were complaints about it.

**Comment by jeenbroekstra** [comment] 2016-11-23 21:11
This bug is the exact cause of SPARQL 1.0 test case "lang-03" failing (see PR #664). If only we had reintegrated those test cases sooner :)

**Comment by jeenbroekstra** [comment] 2016-11-23 21:23
This is related to #449. That issue was originally postponed because we weren't updating to Java 7 just yet. Now that we're a Java 8 club, we should probably have a closer look at it.

**Comment by jeenbroekstra** [comment] 2016-11-23 21:27
As a further point of interest: the request to remove lower-casing all language tags actually came from Vladimir Alexiev of Ontotext. See https://openrdf.atlassian.net/browse/SES-1999 . Also relevant: #478 (which is the migrated issue SES-1659).

**Comment by jeenbroekstra** [comment] 2016-11-23 21:31
The immediate fix for the broken hashcode impl is clear though: we need to either ignore case for language tags in both hashCode and equals, or in neither. I'm in favor of ignoring case in both - that way they behave consistently regardless of the actual case that we store (whether it's all lowercase or follows BCP 47 recommendations). `String.toLowerCase` is sufficiently fast that I don't consider this a significant performance regression (though I'll try and run a benchmark to make sure).

**Comment by jeenbroekstra** [comment] 2016-11-23 21:52
Possible tweak to increase performance is to have a private field that stores the lower-cased tag, and use that in equals and hashCode. I'll run some tests.

**Comment by ansell** [comment] 2016-11-23 22:21
Sorry for confusion in my comment above. Sesame-4.0 removed lowercasing of language tags by default, but it is still available as a parser setting.

I backed out/didn't integrate my BCP47 changes when Sesame-2.8 was decided to be Java-6 compatible. BCP47 requires Java-7 for the BCP47 locale support from the native JDK methods (although there may have been other third-party libraries supporting it for Java-6). 

All previous Sesame releases relied on was RFC3066 because RDF-1.0 referenced it: 

https://www.w3.org/TR/2004/REC-rdf-concepts-20040210/#section-References

Fixing this to comply with RDF-1.1 would require implementing another LanguageHandler for BCP47 in rio-languages, and making it the default in BasicParserSettings, so people could still choose RFC3066 behaviour, but by default it would use BCP47. I will look into this, as I already wrote some code for it back when Sesame-2.8 was being developed.

**Comment by jeenbroekstra** [comment] 2016-11-24 00:07
Turns out I may have been too optimistic about performance. I just ran a few rough benchmarks. Using current implementation, I get ~323 ops/µs throughput on calls to .hashcode. That drops to ~67 ops/µs when adding toLowerCase on language tags that already are all lowercase, and to ~17 ops/µs on language tags that are stored as uppercase.

**Comment by ansell** [comment] 2016-11-24 00:16
I think performance may have been the main reason for only using the literal value in hashcode for many years, before the recent change. Unless there are still convincing reasons why datatype and language tag need to be in the hashcode, I would suggest removing them from it, which would fix this issue, as equals would then be consistent with hashcode.

**Comment by ansell** [comment] 2016-11-24 00:32
There is clear text in RDF-1.1 saying that we are free ("MAY" in RFC2119 language) to lowercase any and all language tags that come through. RDF-1.0 was a little confusing, but if read literally it seems to allow lowercasing of language tags ("It does not constrain an RDF implementation to actually normalize the case." is the language used), which seems to map to a similar behaviour as the "MAY" used in RDF-1.1.

However, I think users are attached in general to the casing of their language tags and expect them to be preserved even though BCP47 specifies case-insensitive behaviour for all parts of all language tags, so we may just need to make it work. 

Hence, I would prefer removing the datatype and language tag from hashcodes as they are irrelevant to whether hashcode produces uniform hashcodes (people don't store enormous numbers of literal values with different language tags or datatypes, and if they do they should expect slight degradation IMO so that the general case is smoother)

**Comment by jeenbroekstra** [comment] 2016-11-24 00:36
Well, this is a followup of #649 , which was a regression bug of the hashCode implementation when migrating from Sesame. That issue was reported by @nikolavp because of a migration problem within GraphDB . I will confer with him. 

There's also the issue that the version of MapDB we use to provide disk overflow in query evaluation (especially for calculating aggregates) (wrongly) relies on hashcode uniqueness, and runs into clashes when comparing a literal with and without a language tag. Or at least I remember that being the case when I implemented it - I will doublecheck this though.

**Comment by ansell** [comment] 2016-11-24 00:39
Those sound like convincing arguments if they are not able to be worked around, but in general adding too many fields to hashcode will degrade performance, so there are penalties to this workaround.

**Comment by jeenbroekstra** [comment] 2016-11-24 01:11
I may be mistaken about my earlier assertion about MapDB - or at least running a few quick tests I have not been able to reproduce any problems when hashcode is label-only.

That leaves GraphDB's internal issue as the main reason in favor of adding language and datatype to hashCode.

Summarizing, we have the following options:

1. we roll back the fix from #649 and make hashCode label-only again.  This is only feasible if there is a viable workaround for GraphDB.
2. we add `toLowerCase` to `hashCode` and accept the performance penalty. Not my preference.
3. we store a private lowercased copy of the language and use that to calculate hashes. Downside is that only `hashCode` can rely on this (the `equals` method cannot access the private field of the other literal), so this is not a very clean solution (and also still has a performance/storage impact).
4. we lowercase/normalize every language tag in the SimpleLiteral constructor.

In my mind, options 2 and 3 are not desirable from a performance/scalability perspective. Option 4 is possible, but with the proviso that some users will be unhappy we no longer preserve their original formatting. 

Options 1, 2 and 3 can all be done in a simple patch release. Option 4 imho changes behavior enough to require a minor release.

**Comment by ansell** [comment] 2016-11-24 01:22
Another option is to use .toLowerCase for hashcode, but store the result as a precomputed hashcode in a new int field so it doesn't need to be recomputed after the first time (or do it in a constructor). Then we only get the long term performance penalty for using .toLowerCase for equals.

**Comment by jeenbroekstra** [comment] 2016-11-24 01:24
That's a good idea, actually, thanks for that.

**Comment by jeenbroekstra** [comment] 2016-11-24 01:43
Still slightly in favor of rolling back #649, also since the actual API documentation for `Literal.hashCode` states:

>  Returns the literal's hash code. The hash code of a literal is defined as the hash code of its label:
	 `label.hashCode()`.

So the implementation that involves language and datatype actually breaks our own API spec.

**Comment by jeenbroekstra** [comment] 2016-11-24 01:55
@nikolavp looking forward to hearing your take on all this when you get back online.

**Comment by nikolavp** [comment] 2016-11-24 09:33
LOL I didn't expect such a huge discussion from this in my opinion "easy fix". I guess nothing is that simple in the semantic technology space. Here is my opinion:

- hashcode & equals must take into account the datatype and language because it's part of the spec(https://www.w3.org/TR/rdf11-concepts/ section 3.3)
```
Literal term equality: Two literals are term-equal (the same RDF literal) if and only if the two lexical forms, the two datatype IRIs, and the two language tags (if any) compare equal, character by character. Thus, two literals can have the same value without being the same RDF term. For example:
``` 
I see the problem with the contract of the API documentation and probably this should be reverted for the next patch release and be included in the next minor?! Not sure about that however GraphDB is going to be released with rdf4j2.0.3 because otherwise you break the contract from sesame 2.8.

- In RDF1.0 it is clearly written that the value for the language tag is lowercased always (https://www.w3.org/TR/2004/REC-rdf-concepts-20040210/#dfn-language-identifier section 6.5)
```
Plain literals have a lexical form and optionally a language tag as defined by [RFC-3066], normalized to lowercase.
```
Note that here rdf4j and sesame always had the correct behaviour in terms of parsing(lowercasing)
https://github.com/eclipse/rdf4j/blob/master/core/rio/languages/src/main/java/org/eclipse/rdf4j/rio/languages/RFC3066LanguageHandler.java#L76
but there might be problems internally with literals created through the factory(the case with which I opened the issue) and probably through SPARQL queries

* In RDF1.1 the spec optionally allows lowercasing and explicitly says that literals should be compared in a lowercase manner. Section 3.3
```
Lexical representations of language tags may be converted to lower case. The value space of language tags is always in lower case.
```
so I think it is *valid* to always lowercase even if we are using BCP47 despite the issue from Vlado - SES-1999 


So I see two options:

* always lowercase in simpleliteral's consturctor - if we want to comply with both RDF1.0 and RDF1.1(it allows it)
* or use the BCP language handler's logic in the constructor to comply with the RDF1.1 spec only

**Comment by jeenbroekstra** [comment] 2016-11-24 21:20
Good points @nikolavp, thanks. I'll respond point by point:

> hashcode & equals must take into account the datatype and language because it's part of the spec(https://www.w3.org/TR/rdf11-concepts/ section 3.3)

I agree that `equals` must take language and datatype into account. I don't agree that `hashCode` must, too. As long as a relatively even distribution of hashcodes is generated given sufficiently different Literal objects, and two Literals that are equal get identical hashcodes, we meet requirements. Basing the hashcode on label only satisfies both those goals, everything else just introduces a performance penalty IMO. 

> I see the problem with the contract of the API documentation and probably this should be reverted for the next patch release and be included in the next minor?! Not sure about that however GraphDB is going to be released with rdf4j2.0.3 because otherwise you break the contract from sesame 2.8.

What I propose is that you just stick with RDF4J 2.0.3 for now, and document the language tag case issue as a known bug. We will release a patch for RDF4J 2.1 (2.1.3) soon, that will revert the changes to hashCode. That way you can upgrade GraphDB to the "corrected" hashcode implementation when you have time to do the wider tests needed to jump from 2.0 to 2.1. Is that workable for you?

As for lowercasing the language tag in the ValueFactory or Literal constructor: I will create a separate issue for that, and if we decide to implement that we will need to make it part of a next minor release (2.2 if we have time). Apart from anything else, a practical problem is that we need to distinguish literals created by a parser (which already has its own language tag normalization) from literals created directly by user code: we don't want to normalize twice (performance penalty), and we also don't want to "override" whatever normalization rules the parser applies - so it's not simply a matter of doing `toLowerCase()` in the `SimpleLiteral` constructor I'm afraid.

**Comment by jeenbroekstra** [comment] 2016-11-24 21:36
I've created two followup issues. The hashcode implementation bug is tracked by #668. The enhancement to do language tag normalization in ValueFactory/SimpleLiteral is tracked by #667. I suggest we close this issue and continue discussion under each of those issues, separately.

**Closed by jeenbroekstra** 2016-11-24 21:36 UTC
Labels: bug, wontfix
