### ISSUE TITLE
connection.remove(Statement) very slow sometimes stuck

### ISSUE THREAD

**Issue by gphmath** [eclipse/rdf4j#1059] opened 2018-08-01 10:47 UTC
Hello,developers!
 I am programming with dependency:
`  	<dependency>`
    `  		<groupId>org.eclipse.rdf4j</groupId>`
    `  		<artifactId>rdf4j-runtime</artifactId>`
    `  		<version>2.3.2</version>`
`  	</dependency>`
And when using HTTPRepository, and use the connection of repository to remove a statement from the repository, it take a long time, more than one minute to remove one statement,sometimes it is stuck for  more than 30 minutes while removing one statement.
`String rdf4jServer = "http://xxx.xxx.xxx.xxx:8080/rdf4j-server/";`
`String repositoryID = "test";`
`Repository repo = new HTTPRepository(rdf4jServer, repositoryID);`
` repo.initialize();`
`try (RepositoryConnection conn = repo.getConnection()) {`
`conn.add(some iri,FOAF.PHONE,phone_number); // add statement is OK`
`conn.remove(some iri,FOAF.PHONE,phone_number); // remove statement will be very slow`
`}`
When removing statements slowly, the rdf4j workbench often cannot open.
I can query smoothly in Python and workbench.
The number of statements in the repository is far less than one million.
Could you please tell me some probable reasons that can  lead to slow removing?
And is this the efficient way to remove statements? Or any other better way to remove that I can try?
If the information is not enough, I will supplement it.

Thank you very much!

**Comment by jeenbroekstra** [comment] 2018-09-04 00:12
Duplicate of discussion on rdf4j-users group (see https://groups.google.com/d/msg/rdf4j-users/tJh2LEH2YHU/gG-Gy2ndCgAJ ), closing as it seems feedback from community has adequately resolved the problem.

**Closed by jeenbroekstra** 2018-09-04 00:12 UTC
