### ISSUE TITLE
Links to API (javadoc) no longer in docs?

### ISSUE THREAD

**Issue by woutermont** [eclipse/rdf4j#1428] opened 2019-05-26 12:20 UTC
Nice job on the new lay-out! However, is there a reason for the docs no longer containing links to the API javadoc? Being able to quickly check out the details of what is presented in the docs is definitely a must.

**Comment by jeenbroekstra** [comment] 2019-05-27 23:07
Looks like there's two issues: 1) we didn't provide a link everwhere and 2) the links to `/javadoc/latest` don't work.

**Comment by jeenbroekstra** [comment] 2019-05-28 09:39
I've fixed the immediate redirect issues. Have a look, let me know if the issue is solved or if I've overlooked something.

**Comment by woutermont** [comment] 2019-05-28 09:43
Redirect from `/latest/` to `/2.5.0/` seems to work fine now. Having the links from the docs to the api javadocs back would be nice though. Is there an easy way to reinsert the links that were present before the update?

**Comment by jeenbroekstra** [comment] 2019-05-28 10:16
Most of them are still there, afaik. Can you point to a specific location where they're missing?

**Comment by jeenbroekstra** [comment] 2019-05-28 10:21
Never mind, just noticed that they are indeed missing in several places (the one place I was looking did have them - figures :)).

**Comment by woutermont** [comment] 2019-05-28 10:25
For a minute, I thought I'd gone blind! As far as I know, all pages I visited since the update contain no links at all in the main tekst (navigational links are present and work, that's not the issue). I was looking for an old version of the docs to compare, but the current repo only contains the migration commit. Which repo where they in before the update?

**Comment by jeenbroekstra** [comment] 2019-05-28 10:36
Same repo, but we just merged a commit that removes them. So you'll need to dig into the history if you want to take a look.

**Comment by jeenbroekstra** [comment] 2019-05-28 23:23
I've fixed this for part of the documentation now, will try and go through the rest ASAP. Thanks again for reporting this!

**Closed** 2019-06-01 03:43 UTC
Labels: :octocat: rdf4j-doc, bug
