### ISSUE TITLE
Queries with sub queries should optimize subquery

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2258] opened 2020-05-23 11:56 UTC
Subqueries are not optimized wrt. their EvaluationStatistics. There is no ordering of joins based on the estimated size of each StatementPattern. 

An easy way to see this is to debug QueryPlanRetrievalTest#testSubQuery with a break point in MemEvaluationStatistics#getCardinality.

**Comment by hmottestad** [comment] 2020-05-23 11:57
@jeenbroekstra did you know that this was the case?

**Comment by jeenbroekstra** [comment] 2020-05-23 22:41
I was not. Good find! I wonder if it more broadly holds for nested group patterns, too, and if this is a recent thing introduced by our changes to join strategy handling, or something that has just never really worked properly (the query join optimizer was written before SPARQL supported subqueries, it's not impossible that we just "forgot" to add this).

**Comment by jeenbroekstra** [comment] 2022-02-07 04:39
Closing this is a duplicate of #3667 (which is more recent, but also has suggestions for a fix).

**Closed by jeenbroekstra** 2022-02-07 04:39 UTC
Labels: duplicate, 📶 enhancement, ⏩ performance
