### ISSUE TITLE
"Cannot retry request with a non-repeatable request entity" exception when uploading triples

### ISSUE THREAD

**Issue by rune66** [eclipse/rdf4j#647] opened 2016-11-11 10:20 UTC
I have made a fresh install of rdf4j 2.1.1 on Tomcat 8.5.

Now I'm trying to add some triples using the workbench->add upload which doesn't work. I get the following exception:

org.apache.http.client.ClientProtocolException
	org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	org.eclipse.rdf4j.http.client.SparqlSession.execute(SparqlSession.java:1102)
	org.eclipse.rdf4j.http.client.SparqlSession.executeNoContent(SparqlSession.java:1083)
	org.eclipse.rdf4j.http.client.SesameSession.upload(SesameSession.java:845)
	org.eclipse.rdf4j.http.client.SesameSession.upload(SesameSession.java:672)
	org.eclipse.rdf4j.http.client.SesameSession.upload(SesameSession.java:661)
	org.eclipse.rdf4j.repository.http.HTTPRepositoryConnection.add(HTTPRepositoryConnection.java:466)
	org.eclipse.rdf4j.workbench.commands.AddServlet.add(AddServlet.java:101)
	org.eclipse.rdf4j.workbench.commands.AddServlet.doPost(AddServlet.java:52)
	org.eclipse.rdf4j.workbench.base.TransformationServlet.service(TransformationServlet.java:96)
	org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:125)
	org.eclipse.rdf4j.workbench.proxy.ProxyRepositoryServlet.service(ProxyRepositoryServlet.java:109)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:213)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.handleRequest(WorkbenchServlet.java:141)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:109)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:120)
	org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:125)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.eclipse.rdf4j.workbench.proxy.CacheFilter.doFilter(CacheFilter.java:62)
	org.eclipse.rdf4j.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:53)

root cause

org.apache.http.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity
	org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:107)
	org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	org.eclipse.rdf4j.http.client.SparqlSession.execute(SparqlSession.java:1102)
	org.eclipse.rdf4j.http.client.SparqlSession.executeNoContent(SparqlSession.java:1083)
	org.eclipse.rdf4j.http.client.SesameSession.upload(SesameSession.java:845)
	org.eclipse.rdf4j.http.client.SesameSession.upload(SesameSession.java:672)
	org.eclipse.rdf4j.http.client.SesameSession.upload(SesameSession.java:661)
	org.eclipse.rdf4j.repository.http.HTTPRepositoryConnection.add(HTTPRepositoryConnection.java:466)
	org.eclipse.rdf4j.workbench.commands.AddServlet.add(AddServlet.java:101)
	org.eclipse.rdf4j.workbench.commands.AddServlet.doPost(AddServlet.java:52)
	org.eclipse.rdf4j.workbench.base.TransformationServlet.service(TransformationServlet.java:96)
	org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:125)
	org.eclipse.rdf4j.workbench.proxy.ProxyRepositoryServlet.service(ProxyRepositoryServlet.java:109)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:213)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.handleRequest(WorkbenchServlet.java:141)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:109)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:120)
	org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:125)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.eclipse.rdf4j.workbench.proxy.CacheFilter.doFilter(CacheFilter.java:62)
	org.eclipse.rdf4j.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:53)

I can't be the only one with this problem?

/Rune

**Comment by jeenbroekstra** [comment] 2016-11-11 23:41
I can't immediately reproduce this.

How are you adding the triples: by URL, by local file upload, or are you using the text area to copy-paste data?

Also: what kind of store are you uploading to? Native, Memory? Any reasoners or other "extras" (lucene, etc) enabled?

Are there any errors or warning in the RDF4J Server logs (http://localhost:8080/rdf4j-server/system/logging/overview.view)?

**Comment by jeenbroekstra** [comment] 2016-11-11 23:46
Possible cause is use of InputStreamEntity (which is non-repeatable) to read an InputStream. We should look into using a [FileEntity](https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/entity/FileEntity.html) instead, if possible.

**Comment by jeenbroekstra** [comment] 2016-11-11 23:48
Btw this should not normally happen: for some reason the initial request failed, the http client tries to redo the request (and fails because it uses an inputstream for its content). It will be interesting to figure out why the request failed (which is why I'd like to see if your server logs show anything).

**Comment by rune66** [comment] 2016-11-14 14:41
Hi Jeen

So it’s happening when I try upload an .nt-file via the add menu in the workbench:


Uploading the same data as rdf works. 

The same problem if I use curl.

Other questions:

- Simple Native Java Store
- No reasoners
- RDF4J Workbench 2.1.1
- Java 1.8.0_112

Server log:

 [Rio fatal] Auf Elementtyp "http:" müssen entweder Attributspezifikationen, ">" oder "/>" folgen. (1, 8) 
 
 Client sent bad request ( 400)org.eclipse.rdf4j.http.server.ClientHTTPException: MALFORMED DATA: Auf Elementtyp "http:" müssen entweder Attributspezifikationen, ">" oder "/>" folgen. [line 1, column 8]

Rolling back transaction due to connection closejava.lang.Throwable: null

at org.eclipse.rdf4j.sail.helpers.AbstractSailConnection.close(AbstractSailConnection.java:224)
at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.close(SailRepositoryConnection.java:199)
at org.eclipse.rdf4j.http.server.repository.RepositoryInterceptor.cleanUpResources(RepositoryInterceptor.java:164)
at org.eclipse.rdf4j.http.server.ServerInterceptor.afterCompletion(ServerInterceptor.java:45)
at org.eclipse.rdf4j.http.server.ServerInterceptor$$FastClassBySpringCGLIB$$3d820688.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
at org.eclipse.rdf4j.http.server.repository.RepositoryInterceptor$$EnhancerBySpringCGLIB$$8ebd78c0.afterCompletion(<generated>)
at org.springframework.web.servlet.HandlerExecutionChain.triggerAfterCompletion(HandlerExecutionChain.java:170)
at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1045)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
at com.github.ziplet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:300)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Unknown Source) 

Client sent bad request ( 400)org.eclipse.rdf4j.http.server.ClientHTTPException: MALFORMED DATA: Auf Elementtyp "http:" müssen entweder Attributspezifikationen, ">" oder "/>" folgen. [line 1, column 8]

at org.eclipse.rdf4j.http.server.repository.statements.StatementsController.getAddDataResult(StatementsController.java:463)
at org.eclipse.rdf4j.http.server.repository.statements.StatementsController.handleRequestInternal(StatementsController.java:125)
at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:147)
at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
at com.github.ziplet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:300)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Unknown Source) 

Regards,
Rune

**Comment by jeenbroekstra** [comment] 2016-11-14 15:29
It's definitely strange that you get this unhelpful error in the Workbench, but the Server log shows that your N-Triples file is syntactically incorrect. Apparently already at line 1. This is what causes the request to fail.

**Comment by rune66** [comment] 2016-11-14 15:36
Strange because since it’s an unmodified export from the workbench of an earlier version om Sesame.

**Comment by jeenbroekstra** [comment] 2016-11-14 15:44
There have been some changes in the N-Triples parser. We updated to a newer version of the spec a few versions of Sesame ago. However I thought those changes were backward-compatible.

Can you copy in a fragment of your N-Triples file? Just the first few lines should do since apparently the problem is right at the start...

**Comment by rune66** [comment] 2016-11-14 15:45
Ok - Thank you:

<http://www.kl.dk/ontologies/kle_emneindeks.owl#_00> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.kl.dk/ontologies/kle_emneindeks.owl#Hovedgruppe> .
<http://www.kl.dk/ontologies/kle_emneindeks.owl#_00> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.kl.dk/ontologies/kle_emneindeks.owl#Hovedgruppe> .
<http://www.kl.dk/ontologies/kle_emneindeks.owl#_00> <http://www.w3.org/2000/01/rdf-schema#label> "Kommunens styrelse" .
<http://www.kl.dk/ontologies/kle_emneindeks.owl#_00> <http://www.kl.dk/ontologies/kle_emneindeks.owl#HgServicesidetekst> "<p>Hovedgruppe 00 'Kommunens styrelse' d\u00E6kker sager der vedr\u00F8rer styrelsen af kommunen som kommune jf. kommunestyrelsesloven. Det g\u00E6lder bl.a. kommunalbestyrelsens konstituering, neds\u00E6ttelse af politiske udvalg, forretningsorden, styrelsesvedt\u00E6gt, kommunens organisation og \u00F8konomiske forvaltning.</p>\n\n<p>Hovedgruppe 00 indeholder ogs\u00E5 grupper, som ikke naturligt kan indplaceres under de \u00F8vrige hovedgrupper. Fx 00.03 'International virksomhed og EU', 00.05 'Bes\u00F8g, repr\u00E6sentation', 00.10 'Integration og udl\u00E6ndinge.'</p>\n\n<p>Sager der g\u00E5r p\u00E5 tv\u00E6rs af flere hovedgrupper, indplaceres under 00.01.10 'Opgaver der d\u00E6kker flere hovedgrupper', oprettet konkret til dette form\u00E5l.</p>\n\n<p>Hovedgruppe 00 omfatter bl.a. sager, der administreres/behandles i henhold til f\u00F8lgende lovgivning:</p>\n<p>\n<ul>\n<li>LBK om folkeskolen (Folkeskoleloven)</li>\n<li>LBK om fonde og visse foreninger (Fondsloven)</li>\n<li>LBK om forpligtende kommunale samarbejder</li>\n<li>LBK om fremgangsm\u00E5den ved ekspropriation vedr\u00F8rende fast ejendom</li>\n<li>LBK om kommunal udligning og generelle tilskud til kommuner (Udligningsloven)</li>\n<li>LBK om kommunernes styrelse (Kommunestyrelsesloven)</li>\n<li>LBK om regionernes finansiering</li>\n<li>LBK om statsgaranti til l\u00E5n til fors\u00F8gsbyggeri (St\u00F8ttet boligbyggeri)</li>\n<li>LBK om ungdomsskoler (Ungdomsskoleloven)</li>\n<li>Lov om en satsreguleringsprocent</li>\n<li>Lov om etablering af den selvejende institution Udbetaling Danmark</li>\n<li>Lov om Folketingets Ombudsmand (Ombudsmandsloven)</li>\n<li>Lov om kommunale borgerservicecentre (Borgerservicecenterloven)</li>\n<li>Lov om midlertidig binding af kommunernes og amtskommunernes overskudslikviditet</li>\n<li>Lov om neds\u00E6ttelse af statstilskuddet til kommuner ved forh\u00F8jelser af kommunale parkeringsindt\u00E6gter</li>\n<li>Lov om offentlighed i forvaltningen (Offentlighedsloven)</li>\n<li>Lov om regionale kulturfors\u00F8g</li>\n<li>Lov om revision af den kommunale inddeling</li>\n<li>Lov om Udbetaling Danmark (Udbetaling Danmark-loven)</li>\n<li>Lov om videreanvendelse af den offentlige sektors informationer (PSI-loven)</li>\n<li>Lov om \u00E6ndringer af landets inddeling i kommuner og regioner og om opl\u00F8sning og udpegelse af forpligtende kommunale samarbejder</li>\n<li>Lov om socialtilsyn (Socialtilsynsloven)</li>\n<li>Lov om \u00E6ndring af lov om Det Centrale Personregister (S\u00E6rlig adressebeskyttelse til personer, som uds\u00E6ttes for trusler mod deres person i forbindelse med \u00E6resrelaterede eller samlivsrelaterede konflikter m.v.) (CPR-loven)</li>\n<li>LBK om biblioteksvirksomhed (Biblioteksloven)</li>\n<li>BEK om beregning af satsreguleringsprocenten m.v.</li>\n<li>BEK om deling af kommuner</li>\n<li>BEK om forretningsorden for b\u00F8rn og unge-udvalgene</li>\n<li>BEK om kommuners l\u00E5ntagning og meddelelse af garantier mv.</li>\n<li>BEK om kommunernes mellemv\u00E6render med de kommunale forsyningsvirksomheder</li>\n<li>BEK af lov om frikommuner m.v. (Frikommuneloven)</li>\n<li>BEK om aktindsigt i visse interne kommunale og regionale dokumenter</li>\n<li>BEK af lov om rettens pleje</li>\n<li>BEK om Udbetaling Danmarks kontoplan m.v.</li>\n<li>BEK om kommunernes budget- og regnskabsv\u00E6sen, revision m.v.</li>\n<li>BEK om \u00E6ndring af bekendtg\u00F8relse om regionernes budget- og regnskabsv\u00E6sen, revision m.v.</li>\n<li>BEK om regnskaber m.v. for Udbetaling Danmark</li>\n<li>BEK af lov om merv\u00E6rdiafgift (momsloven)</li>\n<li>BEK af forvaltningsloven (Forvaltningsloven)</li>\n<li>BEK om organisering og underst\u00F8ttelse af besk\u00E6ftigelsesindsatsen m.v.</li>\n</ul>\n</p>" .
<http://www.kl.dk/ontologies/kle_emneindeks.owl#_00> <http://www.kl.dk/ontologies/kle_emneindeks.owl#Hovedgruppenummer> "00" .
<http://www.kl.dk/ontologies/kle_emneindeks.owl#_00> <http://www.kl.dk/ontologies/kle_emneindeks.owl#Oprettetdato> "1988-01-01"^^<http://www.w3.org/2001/XMLSchema#date> .
<http://www.kl.dk/ontologies/kle_emneindeks.owl#_00> <http://www.kl.dk/ontologies/kle_emneindeks.owl#har_rettelse> <http://www.kl.dk/ontologies/kle_emneindeks.owl#ret_hg_00> .
<http://www.kl.dk/ontologies/kle_emneindeks.owl#_00> <http://www.kl.dk/ontologies/kle_emneindeks.owl#indg\u00E5r_i_delplan> <http://www.kl.dk/ontologies/kle_emneindeks.owl#dp_FolkeskolenDelplan> .
<http://www.kl.dk/ontologies/kle_emneindeks.owl#_00> <http://www.kl.dk/ontologies/kle_emneindeks.owl#indg\u00E5r_i_delplan> <http://www.kl.dk/ontologies/kle_emneindeks.owl#dp_DagtilbudDelplan> .
<http://www.kl.dk/ontologies/kle_emneindeks.owl#_00> <http://www.kl.dk/ontologies/kle_emneindeks.owl#indg\u00E5r_i_delplan> <http://www.kl.dk/ontologies/kle_emneindeks.owl#dp_KommunalVandDelplan> .
<http://www.kl.dk/ontologies/kle_emneindeks.owl#_00> <http://www.kl.dk/ontologies/kle_emneindeks.owl#indg\u00E5r_i_delplan> <http://www.kl.dk/ontologies/kle_emneindeks.owl#dp_SaerligStoetteDelplan> .
<http://www.kl.dk/ontologies/kle_emneindeks.owl#_00> <http://www.kl.dk/ontologies/kle_emneindeks.owl#indg\u00E5r_i_delplan> <http://www.kl.dk/ontologies/kle_emneindeks.owl#dp_JobcenterDelplan> .

**Comment by jeenbroekstra** [comment] 2016-11-16 03:37
Odd - I can upload the fragment you provided just fine, without any errors. Can you verify if the problem still occurs if you only try to upload this fragment? 

If it no longer occurs with this fragment, there might be a problem deeper in the file. Not sure how private your data is, but if possible can you attach a copy of the full file to this issue?

**Comment by jeenbroekstra** [comment] 2016-11-16 03:42
**Update** I think I have found the root cause: you are trying to upload a file of type "N-Triples", but you have the wrong file type selected, or you have "(autodetect)" selected. Unfortunately autodetect does not work properly, this is a known issue ( #67 ). Try uploading by explicitly selecting "N-Triples" in the file format dropdown. 

A secondary issue is that  the error should be reported like this:
![screen shot 2016-11-16 at 14 41 16](https://cloud.githubusercontent.com/assets/728776/20333995/c2f86aae-ac0a-11e6-9ed0-639758b711a2.png)

But instead you get this strange ClientProtocolException

**Comment by rune66** [comment] 2016-11-16 16:17
Hi Jeen

I found out importing in RDF and via looking at the system log, that I problems with non valid RDF:id-names, and also duplicates. Like you said these things weren’t checked in the older Sesame versions.

Only thing is, that the browser and API still throws the not very telling connection exception, when there’s and error in the RDF/XML. I have to go to the system log to see what’s actually wrong.

**Comment by ansell** [comment] 2016-12-19 23:49
One of the implementations of SesameSession.upload (heavily overloaded and there are multiple final paths possible) buffers the content into a ByteArrayInputStream in memory and stores it in a custom implementation of AbstractHttpEntity. It then uses Apache Commons IOUtil.transfer, which seems like it depletes the InputStream, and hence isRepeatable has been set to return false for it. It could be implemented alternatively to be repeatable, given it is already buffering. That could improve debugging for issues like this. 

I found this while reviewing my changes for #684, but I won't change it in that pull request.

**Closed** 2017-05-31 19:04 UTC
Labels: bug
