### ISSUE TITLE
Blank node collision when loading JSON-LD

### ISSUE THREAD

**Issue by skodapetr** [eclipse/rdf4j#778] opened 2017-03-09 20:29 UTC
When loading JSON-LD, the blank node's ID is taken from the jsonld-java library. The library uses a counter to generate blank node ID's. So the blank nodes returned by jsonld-java are same for different files - it. they are "unique" just in the scope of a file . The rdf4j however uses these names to identify the blank nodes even between files.

The problem with this situation can be illustrated on a simple example:
File ```in1.jsonld``` : ``` { "http://localhost/ontology/filePredicate": "in1.jsonld" } ```
File ```in2.jsonld``` : ``` { "http://localhost/ontology/filePredicate": "in2.jsonld" } ```
The Java code: 
```    
public static void main(String[] args) throws Exception {
        Model model = new LinkedHashModel();
        try (InputStream stream = new FileInputStream("in1.jsonld")) {
            model.addAll(Rio.parse(stream, "http://localhost/base", RDFFormat.JSONLD));
        }
        try (InputStream stream = new FileInputStream("in2.jsonld")) {
            model.addAll(Rio.parse(stream, "http://localhost/base", RDFFormat.JSONLD));
        }
        try (OutputStream stream = new FileOutputStream("rdf4j.ttl")) {
            Rio.write(model, stream, RDFFormat.TURTLE);
        }
    }
```
Content of the output file (```rdf4j.ttl```): 
``` 
_:b0 <http://localhost/ontology/filePredicate> "in1.jsonld" , "in2.jsonld" . 
```
while it should be 
```
_:b0 <http://localhost/ontology/filePredicate> "in1.jsonld" .
_:b1 <http://localhost/ontology/filePredicate>  "in2.jsonld" .
```
We would get the same result with Repository, but the code for Model is shorter. 

I also tested similar code with Jena, where I got the expected result.

This behaviour is also not compatible with other loaders. For example, if I load two Turtle files, with two blank nodes of the same identifiers, I should got different blank nodes.  This works as Turtle loader give unique IDs to blank nodes even in different files. However as the jsonld-java "reuse" the identifiers, this does not hold for the JSON-LD.

One solution is to use a wrap for the RdfHandler and modify the blank node's ID (for example add a file based prefix).

The used version of rdf4j is 2.2

**Comment by jeenbroekstra** [comment] 2017-03-09 22:57
Most rdf4j rio parsers use the 'PRESERVE_BNODE_ID' parser setting to govern this (by default it should be false, which means the parser just generates new bnode ids to ensure no clashes occur with existing data in the store). However, the json-ld parser uses an external library, and so is set up slightly differently. We'd need to dig in and see where the root cause is. @ansell are you available to take a look at this in the near future?

**Comment by ansell** [comment] 2017-03-09 23:05
This looks like a duplicate of #745 (title of that bug doesn't indicate its full scope). I have a partial patch for parsers other than JSON-LD at:

https://github.com/eclipse/rdf4j/compare/master...ansell:issues/%23745-parser-resets

Not sure when I will get time to complete that patch though.

**Closed** 2017-05-04 11:10 UTC
Labels: bug
