### ISSUE TITLE
Performance issue in evaluating graph query after upgrade rdf4j from 3.2.0 to 3.2.3

### ISSUE THREAD

**Issue by elbadryt-semantic-web** [eclipse/rdf4j#2735] opened 2020-12-23 14:41 UTC
Hello,

I face some performance issues, after upgrading the rdf4j library version from 3.2.0 to 3.2.3.
since while I was running the following graph query on the attached data, it was taking around 2 minutes but after upgrading it took more than 5 minutes.
and the java code for that is:
` connection.prepareGraphQuery(QueryLanguage.SPARQL, **query**).evaluate();
`
**The query:** 
```
PREFIX h:<urn:pp:internalHelper/>
PREFIX owl:<http://www.w3.org/2002/07/owl#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
PREFIX skosxl:<http://www.w3.org/2008/05/skos-xl#>
PREFIX swcs:<http://schema.semantic-web.at/ppt/>
CONSTRUCT {?c a ?t. ?c a ?t2. } FROM <https://performance.sqa.semantic-web.at/MeSH2016-SQAGPS_ABC-localMemory2/thesaurus> FROM <https://performance.sqa.semantic-web.at/MeSH2016-SQAGPS_ABC-localMemory2/thesaurus/reasoning#592ca235-5e05-4c36-8e77-11d2ba3d6a77> WHERE {
    ?c a ?t.
    FILTER (?t IN (<https://pp-remotestore-test.semantic-web.at/SQA-GPO/GenericClass>))
    FILTER NOT EXISTS {
        ?c (swcs:appliedType|swcs:propagateType)/rdfs:subClassOf* ?t
    }
    FILTER NOT EXISTS {
        ?c ^skos:member ?root. ?root swcs:appliedType/rdfs:subClassOf* ?t
    }
    FILTER NOT EXISTS {
        ?root a skos:OrderedCollection; 
                skos:memberList ?member; 
                <http://schema.semantic-web.at/ppt/appliedType>/rdfs:subClassOf* ?t. 
        ?member rdf:rest*/rdf:first ?c.     }
    FILTER NOT EXISTS {
        ?c (skos:broader|^skos:narrower)+ ?root. ?root swcs:propagateType/rdfs:subClassOf* ?t
    }
    FILTER NOT EXISTS {
        ?c (skos:broader|^skos:narrower)*/(skos:topConceptOf|^skos:hasTopConcept) ?root. ?root swcs:appliedType/rdfs:subClassOf* ?t
    }
    OPTIONAL {?t rdfs:subClassOf* ?t2.} }
 ```

and this is the rdf data 
[pp_project_mesh2016_sqagpsabclocalmemory2.zip](https://github.com/eclipse/rdf4j/files/5735674/pp_project_mesh2016_sqagpsabclocalmemory2.zip)

**semantic-web-company**

**Comment by barthanssens** [comment] 2020-12-23 18:09
Hi,

could you provide some additional info about the hardware and the sail repository configuration / store you're using ? Perhaps inferencing ?

I loaded the data and got 252581 triples, but parsing the query took less than a 0.5 second on a modest Core i5 laptop when using either MemoryStore or NativeStore, not minutes ...

```
Repository repo = new SailRepository(new NativeStore(Files.createTempDirectory("data").toFile()));
File file = Paths.get("c:/data/data.trig").toFile();

try (RepositoryConnection conn = repo.getConnection()) {
	conn.add(file, "", RDFFormat.TRIG);
	System.err.println("size " + conn.size());
			
	Date now = Date.from(Instant.now());
	conn.prepareGraphQuery(QueryLanguage.SPARQL, str).evaluate();
	System.err.println(Date.from(Instant.now()).getTime() - now.getTime());		
}
```

**Comment by jeenbroekstra** [comment] 2020-12-23 22:42
Fwiw I also went ahead and tested this. I also extended the test to retrieve the query result (as a Model):

```java
	Model result = QueryResults.asModel(conn.prepareGraphQuery(str).evaluate());
```

 and tried with several RDF4J versions:

- with RDF4J 3.2.0 this took 37 seconds
- with RDF4J 3.2.3 and 3.5.0 this took 41 seconds

This on my local laptop (Core i7 linux, JDK 11). So there is a slight performance decrease. This could be related to several bug fixes we did in releases 3.2.1-3.2.3 for property path expressions (see #2142 and #2343). But I'm seeing nowhere near the performance decrease you were reporting.

I note, by the way, that the result of the query on the data is empty. This was the same in all versions.

**Comment by hmottestad** [comment] 2020-12-25 18:02
Chiming in here too. 

Could you take a look at this: https://rdf4j.org/documentation/programming/repository/#explaining-queries

And see if the query plan has changed. 

It also has a performance measuring mode that will tell you how much time is used on each part of the query plan.

**Comment by elbadryt-semantic-web** [comment] 2020-12-28 14:27
Hi @barthanssens 
I am using mac os with 2,3 GHz Core i5 and 16GB ram and I am using localMemoryRDF4J

**Comment by barthanssens** [comment] 2020-12-28 15:14
@hmottestad  thanks, very useful
FWIW: on my machine the query plan didn't change between 3.2.0 and 3.2.3, and in both cases totaltime was less than 37 seconds...

**Comment by barthanssens** [comment] 2020-12-30 20:19
@elbadryt-semantic-web 

Could you post the query plan as suggested by @hmottestad  ?

If possible both for 3.2.0 and 3.2.3 so we can check if there is a substantial difference / identify the bottleneck ? On my machine the difference is still neglectable, so the query plan may help to reproduce the issue ... Thanks

E.g.
```
	GraphQuery query = conn.prepareGraphQuery(QueryLanguage.SPARQL, str);
	String explanation = query.explain(Explanation.Level.Timed).toString();
	System.err.println(explanation);
```

**Comment by elbadryt-semantic-web** [comment] 2021-01-04 10:25
Hi @barthanssens 

The attached file contains the plan for 3.2.3, I couldn't get 3.2.0 because it causes some conflicts when I change the version, and sorry for the late reply I was on holiday.


[plan.txt](https://github.com/eclipse/rdf4j/files/5764176/plan.txt)

**Comment by elbadryt-semantic-web** [comment] 2021-01-04 10:31
Also this data is more accurate regarding, The issue but when I tried it in sperate unit test class it works fast as you said, but the problem happen in project and I couldn't find the diffrence between unit test class and in our project.

[allDataa.trig.zip](https://github.com/eclipse/rdf4j/files/5764206/allDataa.trig.zip)

**Comment by barthanssens** [comment] 2021-01-04 11:50
Ow, that’s both good and bad news…
Difficult to tell what the exact problem is without looking at the code (I assume the project you’re working on is not open source)

Does your project perhaps wrap the memory/nativestore in an additional SAIL ?
E.g ForwardChainingRDFSInferencer or SchemaCachingRDFSInferencer

Could there be some kind of locking active ?
E.g in a transaction with a specific IsolationLevel ?

Or could there be anything special in the way the statements are collected after evaluation ?
E.g added to another Model or Repository ?


Best regards

Bart

**Comment by hmottestad** [comment] 2021-01-04 14:16
> Hi @barthanssens 
> 
> 
> 
> The attached file contains the plan for 3.2.3, I couldn't get 3.2.0 because it causes some conflicts when I change the version, and sorry for the late reply I was on holiday.
> 
> 
> 
> 
> 
> [plan.txt](https://github.com/eclipse/rdf4j/files/5764176/plan.txt)
> 
> 

The plans are only really useful if they can be compared between versions!

**Comment by elbadryt-semantic-web** [comment] 2021-01-05 20:45
Hi again,
I still couldn't reproduce the huge performance issue in the unit test.
but now after some checks with data and query, it now takes 32 seconds or more.
So can you check to run the following query on the attached file, also with this minor change on the code.
Query:

PREFIX h:<urn:pp:internalHelper/>
PREFIX owl:<http://www.w3.org/2002/07/owl#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
PREFIX skosxl:<http://www.w3.org/2008/05/skos-xl#>
PREFIX swcs:<http://schema.semantic-web.at/ppt/>
CONSTRUCT {?c a ?t. ?c a ?t2. } FROM <https://performance.sqa.semantic-web.at/MeSH2016-SQAGPS_ABC-localMemory2/thesaurus> FROM <https://performance.sqa.semantic-web.at/MeSH2016-SQAGPS_ABC-localMemory2/thesaurus/reasoning#ffa27dac-01b9-442f-b57a-a821caf613d6> WHERE {
    ?c a ?t.
    FILTER (?t IN (<https://pp-remotestore-test.semantic-web.at/SQA-GPO/GenericClass>))
    FILTER NOT EXISTS {
        ?c (swcs:appliedType|swcs:propagateType)/rdfs:subClassOf* ?t
    }
    FILTER NOT EXISTS {
        ?c ^skos:member ?root. ?root swcs:appliedType/rdfs:subClassOf* ?t
    }
    FILTER NOT EXISTS {
        ?root a skos:OrderedCollection; 
                skos:memberList ?member; 
                <http://schema.semantic-web.at/ppt/appliedType>/rdfs:subClassOf* ?t. 
        ?member rdf:rest*/rdf:first ?c.     }
    FILTER NOT EXISTS {
        ?c (skos:broader|^skos:narrower)+ ?root. ?root swcs:propagateType/rdfs:subClassOf* ?t
    }
    FILTER NOT EXISTS {
        ?c (skos:broader|^skos:narrower)*/(skos:topConceptOf|^skos:hasTopConcept) ?root. ?root swcs:appliedType/rdfs:subClassOf* ?t
    }
    OPTIONAL {?t rdfs:subClassOf* ?t2.} }


and for the java code please follow the following code:

Repository repo = new SailRepository(new MemoryStore(Files.createTempDirectory("data").toFile()));
        File file = Paths.get("/Volumes/My Files/allDataa.trig").toFile();
        try (RepositoryConnection conn = repo.getConnection()) {
            conn.add(file, "", RDFFormat.TRIG);
            Date now = Date.from(Instant.now());
            Set<Statement> statements=new HashSet<>();
            conn.prepareGraphQuery(QueryLanguage.SPARQL, query).evaluate(new StatementCollector(statements));
            System.err.println(Date.from(Instant.now()).getTime() - now.getTime());
        }

and this is the file with the data :
[allDataa.trig v2.zip](https://github.com/eclipse/rdf4j/files/5772480/allDataa.trig.v2.zip)

So when I ran this query using this java code on the attached data it took nearly 30 to 35 seconds,
I also tried the same query on this data in the rdf4j standalone server from rdf4j workbench and it takes the same time.
#semantic-web-company

**Comment by hmottestad** [comment] 2021-01-05 20:58
Could you tell us what you changed in the query?

**Comment by elbadryt-semantic-web** [comment] 2021-01-05 21:34
not actual change, I just change the context (graphs) after FROM clause, because it is somehow generated randomly in the project, So I just needed to make sure it the correct graph, but it is not a query change.

**Comment by hmottestad** [comment] 2021-01-05 21:51
So maybe the difference is that the original query had to look at less data than this query?

**Comment by hmottestad** [comment] 2021-01-05 21:53
From the query plan you posted it seems that the slowest part of your query are two of your property paths. You should try to simplify your query to see if you can make a small query that reproduces the performance issue.

**Comment by elbadryt-semantic-web** [comment] 2021-01-05 22:53
No, both queries look at the same volumes of data, but the change of java code from 
  connection.prepareGraphQuery(QueryLanguage.SPARQL, **query**).evaluate();
to 
  Set statements=new HashSet<>();
  conn.prepareGraphQuery(QueryLanguage.SPARQL, query).evaluate(new StatementCollector(statements));

was the trigger to make it take 30 seconds and more, and If I change it back to the old java code, it is finished in less than half-second, and in the project, it uses the second code, but if I changed the code even for the first one in the project, it doesn't enhance the performance of it.
But I don't know what is the difference between those 2 codes.

and for the second reply, what is these 2 properties, and how could I simplify my query if you have some recommendations.
Thanks

**Comment by hmottestad** [comment] 2021-01-05 23:14
Read through this documentation on how query explanation works: https://rdf4j.org/documentation/programming/repository/#explaining-queries

This should help you read the query explanation you created and find those two property paths that I noticed were taking up most of your time. I didn't look further to try to figure out what part of your query it mapped to.

Once you've found out what part of the query is taking the most time, try to remove other parts of the query that you think have little effect to see what happens. It's your query, so I expect you understand what it is supposed to do.

The difference you are seeing with your code is presume is because 
`connection.prepareGraphQuery(QueryLanguage.SPARQL, **query**).evaluate();` returns an iterator and you are not reading anything from it.

**Comment by jeenbroekstra** [comment] 2021-01-06 02:27
> No, both queries look at the same volumes of data, but the change of java code from
> connection.prepareGraphQuery(QueryLanguage.SPARQL, **query**).evaluate();
> to
> Set statements=new HashSet<>();
> conn.prepareGraphQuery(QueryLanguage.SPARQL, query).evaluate(new StatementCollector(statements));
> 
> was the trigger to make it take 30 seconds and more, and If I change it back to the old java code, it is finished in less than half-second, and in the project, it uses the second code, but if I changed the code even for the first one in the project, it doesn't enhance the performance of it.
> But I don't know what is the difference between those 2 codes.

The difference is that in the first case, you're calling `evaluate()`, which gives you back a `QueryResult` object, but you're not doing anything with that result object (like iterating over it, or sticking it in a Collection). RDF4J uses lazy evaluation and won't _actually_ execute the query until you start iterating over the result.

**Comment by elbadryt-semantic-web** [comment] 2021-01-07 12:57
Hi, 
Now I could reproduce the performance issue on unit testing, and it happens when I run the GraphQuery.evaluate() method multiple time before running it on my query, whatever the query I ran before my query, it might be my query or any other query, but when try to run my query after these multiple calls for "evaluate" method, it takes more time, and the more times I call this evaluate method, the much time it takes when I run my query.

So, what do you think about that?

**Comment by hmottestad** [comment] 2021-01-07 15:30
Can you post a fully working example so we can reproduce it?

**Comment by elbadryt-semantic-web** [comment] 2021-01-07 16:28
Hi, yes this the example I used, I just duplicate the code to evaluate some query, and last I evaluate the desired query
I used the data from the attached file

[allDataa.trig v2.zip](https://github.com/eclipse/rdf4j/files/5782782/allDataa.trig.v2.zip)
[TestRdf4j2.java.zip](https://github.com/eclipse/rdf4j/files/5782773/TestRdf4j2.java.zip)

**Comment by barthanssens** [comment] 2021-01-07 19:52
Thanks for the code example.

Running on my machine, there is indeed a clear difference between the invalid (0.3 s) and the correct query (+/- 28 s), but I still don't see much difference between RDF4J 3.2.0 and 3.2.3 (running the test a few times always returns timings between 27 and 30 s for both 3.2 and 3.2.3, mostly because the CPU of my laptop is throttling) .

On my machine, there is also no difference for the timing of the correct query when running the invalid queries + correct query, and when running only the correct query...

**Comment by hmottestad** [comment] 2021-02-01 10:00
Closing this as we are unable to reproduce any of the issues mentioned.

**Closed by hmottestad** 2021-02-01 10:00 UTC
Labels: 🤔 question
