### ISSUE TITLE
Create HDT Binary RDF Parser and Writer for Sesame Rio

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#434] opened 2016-09-07 00:19 UTC
(Migrated from https://openrdf.atlassian.net/browse/SES-1874)

The HDT format is a proposed binary format for RDF that has been given in a member submission to the W3C. It would be useful to have a HDT parser and writer for Sesame Rio to provide another binary RDF alternative.

http://www.w3.org/Submission/2011/SUBM-HDT-20110330/

**Comment by barthanssens** [comment] 2016-11-18 09:47
Seems like a duplicate of #232 : at one point an initial version of HDT was proposed to W3C, but further developed outside W3C (rdfhdt.org)

**Closed** 2017-01-31 22:09 UTC
Labels: duplicate
