### ISSUE TITLE
Several testsuite tests  flagging lots of assertions in algebra.Var.setParentNode(Var.java:112)

### ISSUE THREAD

**Issue by nguyenm100** [eclipse/rdf4j#4169] opened 2022-09-09 17:49 UTC
### Current Behavior

SPARQLQueryTest, SPARQLUpdateTest, ComplexSPARQLQueryText,  W3CApprovedSPARQL11QueryTest

~15 tests are failing as a result of some variant of this.

Some stacks:

java.lang.AssertionError
	at org.eclipse.rdf4j.query.algebra.Var.setParentNode(Var.java:112)
	at org.eclipse.rdf4j.query.algebra.BinaryValueOperator.setLeftArg(BinaryValueOperator.java:70)
	at org.eclipse.rdf4j.query.algebra.BinaryValueOperator.<init>(BinaryValueOperator.java:46)
	at org.eclipse.rdf4j.query.algebra.SameTerm.<init>(SameTerm.java:26)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.CompareOptimizer$CompareVisitor.meet(CompareOptimizer.java:59)
	at org.eclipse.rdf4j.query.algebra.Compare.visit(Compare.java:89)
	at org.eclipse.rdf4j.query.algebra.Filter.visitChildren(Filter.java:77)
	
	
java.lang.AssertionError
at org.eclipse.rdf4j.query.algebra.Var.setParentNode(Var.java:112)
at org.eclipse.rdf4j.query.algebra.FunctionCall.addArg(FunctionCall.java:92)
at org.eclipse.rdf4j.query.algebra.FunctionCall.addArgs(FunctionCall.java:79)
at org.eclipse.rdf4j.query.algebra.FunctionCall.<init>(FunctionCall.java:48)
at org.eclipse.rdf4j.query.algebra.evaluation.impl.RegexAsStringFunctionOptimizer$RegexAsStringFunctionVisitor.containsCandidate(RegexAsStringFunctionOptimizer.java:77)
at org.eclipse.rdf4j.query.algebra.evaluation.impl.RegexAsStringFunctionOptimizer$RegexAsStringFunctionVisitor.meet(RegexAsStringFunctionOptimizer.java:68)
at org.eclipse.rdf4j.query.algebra.Regex.visit(Regex.java:71)
at org.eclipse.rdf4j.query.algebra.BinaryValueOperator.visitChildren(BinaryValueOperator.java:96)
at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetNode(AbstractQueryModelVisitor.java:576)
at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetBinaryValueOperator(AbstractQueryModelVisitor.java:545)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meet(AbstractQueryModelVisitor.java:118)
at org.eclipse.rdf4j.query.algebra.And.visit(And.java:35)

java.lang.AssertionError
at org.eclipse.rdf4j.query.algebra.Var.setParentNode(Var.java:112)
at org.eclipse.rdf4j.query.algebra.StatementPattern.<init>(StatementPattern.java:101)
at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:1486)
at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:237)
at org.eclipse.rdf4j.query.parser.sparql.ast.ASTPathElt.jjtAccept(ASTPathElt.java:32)
at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:1411)
at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:237)
at org.eclipse.rdf4j.query.parser.sparql.ast.ASTPathSequence.jjtAccept(ASTPathSequence.java:30)
at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:1358)
at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:237)
at org.eclipse.rdf4j.query.parser.sparql.ast.ASTPathAlternative.jjtAccept(ASTPathAlternative.java:28
	

### Expected Behavior

No assert errors

### Steps To Reproduce

Run testsuite on files: SPARQLQueryTest, SPARQLUpdateTest, ComplexSPARQLQueryText,  W3CApprovedSPARQL11QueryTest

### Version

4.1.2-SNAPSHOT

**Comment by jeenbroekstra** [comment] 2022-09-16 22:54
I know @hmottestad has recently gone over quite a lot of the codebase to rectify this (see GH-4189 and GH-4157). Are these problems still occurring or has this now been rectified?

**Comment by nguyenm100** [comment] 2022-09-17 11:46
[Test Results - com_msd_gin_halyard_strategy_in_halyard-strategy.txt](https://github.com/eclipse/rdf4j/files/9591552/Test.Results.-.com_msd_gin_halyard_strategy_in_halyard-strategy.txt)

Exported as .html but had to rename it to .txt to upload here.  Still about 14 assertions firining on 4.1.3.

**Comment by nguyenm100** [comment] 2022-09-17 13:04
[Test Results - com_msd_gin_halyard_strategy_in_halyard-strategy.txt](https://github.com/eclipse/rdf4j/files/9591727/Test.Results.-.com_msd_gin_halyard_strategy_in_halyard-strategy.txt)

Still occuring on 4.1.3 (see attached -- had to rename from .html to .txt to upload to comment here)

**Comment by hmottestad** [comment] 2022-10-11 04:45
Could you create a pull request to reproduce these issues as I'm having a hard time reproducing them myself.

**Comment by nguyenm100** [comment] 2022-10-12 10:18
just to sync, but were you able to wire up the tests mentioned here and still not seeing an issue? if so, maybe a halyard issue.

**Comment by hmottestad** [comment] 2022-10-12 13:39
This is what I did: https://github.com/eclipse/rdf4j/pull/4211

Was it one of those tests?

**Comment by nguyenm100** [comment] 2022-10-14 18:44
I reran the tests w/o halyard stuff and no more asserts.  However, one of the test is failing and incorrect (tested against graphdb and docker rdf4j 4.2.0.  graphdb returns correct result, 4.2.0 does not.  It appears to also be broken in 4.1.0; i did not go back further).

test is sparql11-exists-06

input data:

@prefix : <http://example/> .

:a :p 1 ; :q 1, 2 .
:b :p 3.0 ; :q 4.0, 5.0 .

query:

PREFIX : <http://example/>
SELECT * WHERE {
	?a :p ?n
	FILTER NOT EXISTS {
		?a :q ?m .
		FILTER(?n = ?m)
	}
}


==========================================================================================
# Expected bindings:

a=http://example/b n="3.0"^^<http://www.w3.org/2001/XMLSchema#decimal> 
==========================================================================================
# Actual bindings:

a=http://example/a n="1"^^<http://www.w3.org/2001/XMLSchema#integer> 
a=http://example/b n="3.0"^^<http://www.w3.org/2001/XMLSchema#decimal> 
==========================================================================================
# Unexpected bindings: 

a=http://example/a n="1"^^<http://www.w3.org/2001/XMLSchema#integer> 
==========================================================================================

**Comment by hmottestad** [comment] 2022-10-28 12:48
Query plan:

```
Projection (resultSizeActual=2)
╠══ProjectionElemList
║     ProjectionElem "a"
║     ProjectionElem "n"
╚══Filter (resultSizeActual=2)
   ├──Not
   │     Exists
   │        Filter (resultSizeActual=0)
   │        ╠══Compare (=)
   │        ║     Var (name=n)
   │        ║     Var (name=m)
   │        ╚══StatementPattern (resultSizeEstimate=8, resultSizeActual=4)
   │              Var (name=a)
   │              Var (name=_const_f65eef3a_uri, value=http://example/q, anonymous)
   │              Var (name=m)
   └──StatementPattern (resultSizeEstimate=4, resultSizeActual=2)
         Var (name=a)
         Var (name=_const_f65eef39_uri, value=http://example/p, anonymous)
         Var (name=n)
```

**Comment by hmottestad** [comment] 2022-10-28 12:54
It works if I change the query to:

```
PREFIX : <http://example/>
SELECT * WHERE {
	?a :p ?n
	FILTER NOT EXISTS {
		?a :q ?n .
	}
}
```

**Comment by hmottestad** [comment] 2022-10-30 16:51
I'm closing this issue since the original issue was about the assert in the Var class. I've create a new issue for the `EXISTS` scoping issue. https://github.com/eclipse/rdf4j/issues/4256

**Closed by hmottestad** 2022-10-30 16:51 UTC
Labels: 🐞 bug
