### ISSUE TITLE
GraphDB: Incompatible format version: 2

### ISSUE THREAD

**Issue by maxstolze** [eclipse/rdf4j#3899] opened 2022-05-16 07:20 UTC
### Current Behavior

Can not communicate with RDF4J 4.0.1 and GraphDB 9.11.1 (based on RDF4J 3.7.6) due to: `Transaction handling error: Incompatible format version: 2`

```
[...]
Caused by: org.eclipse.rdf4j.repository.RepositoryException: Transaction handling error: Incompatible format version: 2
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.execute(SPARQLProtocolSession.java:1070) ~[rdf4j-http-client-4.0.1.jar:4.0.1]
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.executeNoContent(SPARQLProtocolSession.java:1024) ~[rdf4j-http-client-4.0.1.jar:4.0.1]
	at org.eclipse.rdf4j.http.client.RDF4JProtocolSession.upload(RDF4JProtocolSession.java:1102) ~[rdf4j-http-client-4.0.1.jar:4.0.1]
	at org.eclipse.rdf4j.http.client.RDF4JProtocolSession.upload(RDF4JProtocolSession.java:925) ~[rdf4j-http-client-4.0.1.jar:4.0.1]
	at org.eclipse.rdf4j.http.client.RDF4JProtocolSession.removeData(RDF4JProtocolSession.java:910) ~[rdf4j-http-client-4.0.1.jar:4.0.1]
	at org.eclipse.rdf4j.repository.http.HTTPRepositoryConnection.removeModel(HTTPRepositoryConnection.java:574) ~[rdf4j-repository-http-4.0.1.jar:4.0.1]
	at org.eclipse.rdf4j.repository.http.HTTPRepositoryConnection.flushTransactionState(HTTPRepositoryConnection.java:594) ~[rdf4j-repository-http-4.0.1.jar:4.0.1]
	at org.eclipse.rdf4j.repository.http.HTTPRepositoryConnection.add(HTTPRepositoryConnection.java:440) ~[rdf4j-repository-http-4.0.1.jar:4.0.1]
	at org.eclipse.rdf4j.repository.base.RepositoryConnectionWrapper.add(RepositoryConnectionWrapper.java:151) ~[rdf4j-repository-api-4.0.1.jar:4.0.1]
	at org.eclipse.rdf4j.repository.base.RepositoryConnectionWrapper.add(RepositoryConnectionWrapper.java:151) ~[rdf4j-repository-api-4.0.1.jar:4.0.1]
	at org.eclipse.rdf4j.spring.resultcache.CachingRepositoryConnection.add(CachingRepositoryConnection.java:138) ~[rdf4j-spring-4.0.1.jar:4.0.1]
	at org.eclipse.rdf4j.repository.base.RepositoryConnectionWrapper.add(RepositoryConnectionWrapper.java:151) ~[rdf4j-repository-api-4.0.1.jar:4.0.1]
	at org.eclipse.rdf4j.spring.tx.TransactionalRepositoryConnection.add(TransactionalRepositoryConnection.java:74) ~[rdf4j-spring-4.0.1.jar:4.0.1]
	at org.eclipse.rdf4j.repository.RepositoryConnection.add(RepositoryConnection.java:694) ~[rdf4j-repository-api-4.0.1.jar:4.0.1]
	at org.eclipse.rdf4j.spring.tx.TransactionalRepositoryConnection.add(TransactionalRepositoryConnection.java:181) ~[rdf4j-spring-4.0.1.jar:4.0.1]
[...]
```

### Expected Behavior

Working communication with the GraphDB.

### Steps To Reproduce

1. RDF4J 4.0.1 + GraphDB 9.11.1 on Windows 10
2. Try to establish a connection
3. Receive error

### Version

4.0.1

**Comment by hmottestad** [comment] 2022-05-16 07:43
@jeenbroekstra I know you mentioned something in your email, does this align with what you wrote? Is it something we should consider a bug, as in that we want to backwards compatible with older servers?

@maxstolze I'm not sure what your use case is, so I would like to ask if you are unable to upgrade the client and server versions in tandem and need to support both older and newer servers with the same client? The next major GraphDB release should use RDF4J 4.0.

**Comment by jeenbroekstra** [comment] 2022-05-16 07:50
It is yes, but I need to look a bit closer at what's going on here, and what's possible workarounds or fixes are.

**Comment by fkleedorfer** [comment] 2022-05-16 09:20
If there is anything we (@maxstolze is a colleague of mine) can do to shed more light on the issue, please let us know!

**Comment by jeenbroekstra** [comment] 2022-05-16 10:20
Probable cause is that the HTTPRepositoryConnection hardcodes use of the binary format for serializing a model that is being added/removed as part of a transaction. The problem is that the client-side binary format is version ahead of the server, so the server can't parse the request.

Possible fix is to rely on the configured preferred RDF format instead, which would  allow you to configure it to use another format for the serialization.

**Comment by jeenbroekstra** [comment] 2022-05-16 10:30
Actually @fkleedorfer  and @maxstolze  there is a workaround you could try: the Binary RDF Writer can be explicitly configured to use the older format. In your client application, try setting the system property `org.eclipse.rdf4j.rio.binary.format_version` to `1`. See https://rdf4j.org/javadoc/latest/org/eclipse/rdf4j/rio/helpers/BinaryRDFWriterSettings.html#VERSION

**Comment by maxstolze** [comment] 2022-05-16 11:56
Workaround seems to work here. Thx!

**Comment by jeenbroekstra** [comment] 2022-05-16 23:11
I'll close this with a "won't fix" then as there is an acceptable workaround for this situation. Thanks!

**Closed by jeenbroekstra** 2022-05-16 23:11 UTC
Labels: 🐞 bug
