### ISSUE TITLE
"Multiple statements for pattern" error when attempting to load RDF file w/ SPIN constraints

### ISSUE THREAD

**Issue by gwcox66** [eclipse/rdf4j#195] opened 2016-06-24 19:03 UTC
I'm using Sesame OpenRDF Workbench:

> System Information
> Application Information
> Application Name    OpenRDF Workbench
> Version 4.1.2
> Runtime Information
> Operating System    Windows 8.1 6.3 (amd64)
> Java Runtime    Oracle Corporation Java HotSpot(TM) 64-Bit Server VM (1.8.0_91)
> Process User    Greg
> Memory
> Used    357 MB
> Maximum 3463 MB

My constraints, classes, properties, and example individuals are contained in one RDF file under TopBraid Composer Free Edition (attached).  I'm attempting to load into a repository of type "In Memory Store with SPIN+RDFS support".  Screen grab of full error page is also attached.

I've tried using the Sesame Open RDF workbench Modify/Add command to pull in the RDF file generated by TopBraid Free Edition, but I get an error that appears to be related to a blank node:

> javax.servlet.ServletException: org.openrdf.repository.RepositoryException: org.openrdf.repository.RepositoryException: org.openrdf.sail.SailException: org.openrdf.query.QueryEvaluationException: Multiple statements for pattern: _:node1alqlr2eix590 http://spinrdf.org/sp#where null

[SXXIComplianceCheck2.zip](https://github.com/eclipse/rdf4j/files/332392/SXXIComplianceCheck2.zip)
![image](https://cloud.githubusercontent.com/assets/20132242/16347819/59d8e84a-3a14-11e6-878e-099d154e955b.png)

**Comment by pulquero** [comment] 2016-06-24 21:59
I believe that error is due to that pattern resulting in more than one matching statement, I.e. multiple where clauses. I assume you are loading into an empty repository?

**Comment by gwcox66** [comment] 2016-06-24 22:33
Yes, I was loading into an empty repository, and because of this error, the repository remains empty.  No facts were loaded.

For your convenience, here's the SPARQL source code (from TopBraid Composer Free).  This should be the only SPIN constraint remaining in the RDF file...

```
# A proposal with no security classification (data item 005) is not valid
ASK WHERE {
    ?this a sxxicc:Pub7Proposal .
    OPTIONAL {
        ?this sxxicc:pub7ProposalHasDataItem ?dataItem .
        ?dataItem a sxxicc:Pub7DataItem005 .
        ?dataItem sxxicc:pub7DataItemHasStringValue ?securityClassificationString .
    } .
    FILTER ((!bound(?dataItem)) || (!bound(?securityClassificationString))) .
}
```

I supposed the OPTIONAL clause is probably viewed as the second pattern.

BTW, I know that the first triple in the WHERE clause should be redundant because this is a SPIN constraint on the Pub7Proposal class.  I have tried removing that, but the result is the same.

**Comment by gwcox66** [comment] 2016-06-25 19:52
As a further experiment, I simplified the query to omit the `OPTIONAL ` clause.  

```
# A proposal with no security classification (data item 005) is not valid
ASK WHERE {
    ?this sxxicc:pub7ProposalHasDataItem ?dataItem .
    ?dataItem a sxxicc:Pub7DataItem005 .
    ?dataItem sxxicc:pub7DataItemHasStringValue ?securityClassificationString .
}
```

Sadly, this resulted in the same error message.

I've attached the RDF file created in TopBraid Composer Free Edition containing the above simplified SPIN constraint.

[SXXIComplianceCheck4.zip](https://github.com/eclipse/rdf4j/files/333254/SXXIComplianceCheck4.zip)

**Comment by gwcox66** [comment] 2016-06-25 20:53
As a still further experiment, I removed all SPIN constraints entirely, and the resulting RDF file (enclosed) loaded without errors:

```
Summary
Repository Location
ID	SPINRepository
Title	SPIN Experimental Repository
Location	http://localhost:8088/openrdf-sesame/repositories/SPINRepository
Sesame server	http://localhost:8088/openrdf-sesame
Repository Size
Number of Statements	1301
Number of Labeled Contexts	1
```
[SXXIComplianceCheck5.zip](https://github.com/eclipse/rdf4j/files/333287/SXXIComplianceCheck5.zip)

**Comment by pulquero** [comment] 2016-06-26 10:25
When I said "multiple where clauses" I meant something akin to "ask where {...} where {...}". The problem appears to be because the file was loaded with a context. Try setting the context to be empty. There are some subtleties with inferencing over quads that means it isnt easy to make it work.

**Comment by gwcox66** [comment] 2016-06-26 22:24
Thank you pulquero.  I removed the context, and that helped. It left me with compliance violations from my instantiations.  I removed my instantiations, and the resulting RDF file did load.  Now on to further testing.  I can instantiate my classes by other means.

**Comment by jeenbroekstra** [comment] 2016-06-27 20:29
Just doublechecking: does this mean you have found the problem and we can close the issue?

**Comment by gwcox66** [comment] 2016-06-27 22:48
jeenbroekstra, I'll have to leave the close call to others.  Perhaps pulquero could comment, and I would defer.  As for me, I would view what I'm doing now as a workaround.  I would not think that merely loading an RDF file into the default context versus a default-named context (using the workbench) would cause the RDF file to fail to load entirely.  However, I am not an expert in using multiple contexts.  My work to date has been entirely in one context.

**Comment by jeenbroekstra** [comment] 2016-06-28 00:19
I agree that ideally, the SPIN reasoner should be able to deal with contexts more gracefully. This was a known issue for some time but we decided to release with the current state as getting this working is non-trivial. @pulquero I'll leave it up to you to decide if you wish to rewrite this issue to cover the enhancements needed, or if you prefer to open a new enhancement issue and then close this bug report. The latter has my (slight) preference (keeps the changelog cleaner :) ) but whatever works best for you.

**Comment by pulquero** [comment] 2016-06-30 21:02
For the time being I will work under this one because I think I know what the issue is in this particular case and how to fix it.

**Closed** 2016-07-06 21:27 UTC
Labels: bug
