### ISSUE TITLE
Prefixed graph names in trig files expand to null in Statement's

### ISSUE THREAD

**Issue by RickMoynihan** [eclipse/rdf4j#254] opened 2016-07-20 12:15 UTC
This bug occurs against *Sesame 2.8.9*; and I have not yet confirmed its presence in RDF4j (though I've not seen any bugs mentioning this in the old Sesame JIRA).  So suspect it's still an issue.

When parsing a trig file like this:

````
@prefix graph: <http://example.org/graph/> .
@prefix exid: <http://example.org/id/> .

graph:1 {
   exid:1 exid:1 exid:1 .
   exid:2 exid:2 exid:2 .
}

graph:2 {
   exid:1 exid:1 exid:1 .
   exid:2 exid:2 exid:2 .
}

graph:3 {
   exid:1 exid:1 exid:1 .
   exid:2 exid:2 exid:2 .
}
````

The statements that are parsed have their context (graph) set to null.

The following file will however parse correctly:

````
@prefix exid: <http://example.org/id/> .

<http://graph/1> {
   exid:1 exid:1 exid:1 .
   exid:2 exid:2 exid:2 .
}

<http://graph/2> {
   exid:1 exid:1 exid:1 .
   exid:2 exid:2 exid:2 .
}

<http://graph/3> {
   exid:1 exid:1 exid:1 .
   exid:2 exid:2 exid:2 .
}
````

**Comment by jeenbroekstra** [comment] 2016-07-21 03:23
At a guess I'd say this has to do with the fact that `graph:1` was not a legal prefixed name in TriG (the localname part of prefixed name can not start with a number). Or at least this was the case in the old spec - it's probably been updated in the new TriG spec but not yet fixed in our parser.

**Comment by jeenbroekstra** [comment] 2016-07-21 03:27
More generally I'd say that we need to take another good look at both the Turtle and the TriG parser and update them to be compliant against the latest specs.

**Comment by ansell** [comment] 2016-07-21 03:48
I thought that both Turtle and Trig had been updated to RDF-1.1 way back in Sesame-2.7, but may have missed something when I did it.

**Comment by ansell** [comment] 2016-07-21 03:53
For Turtle and Trig, that share very similar compliance test suites in RDF-1.1, there is a test that should be run which verifies localName's can have an integer, although it may be missing corner cases such as the graph name and there may be a small change needed there:

https://github.com/eclipse/rdf4j/blob/master/testsuites/rio/src/main/resources/testcases/turtle/tests-ttl-w3c-20131121/localName_with_leading_digit.ttl

https://github.com/eclipse/rdf4j/blob/master/testsuites/rio/src/main/resources/testcases/trig/localName_with_leading_digit.trig

**Comment by jeenbroekstra** [comment] 2016-07-21 08:20
@ansell I may have been misled by the Javadoc in both parsers, which still quotes the old (pre-W3C) specs as leading the implementation. I guess we should update that then :)

**Comment by RickMoynihan** [comment] 2016-07-21 10:18
Thanks for looking into this...  It does look like the spec allows numbers for [PN_CHARS](https://www.w3.org/TR/trig/#grammar-production-PN_CHARS).

Incidentally I tried updating my file to have `graph:a` as the graph clause and it still seems to come out as null.

**Comment by ansell** [comment] 2016-07-21 22:55
I will try to make time today to write up a set of regression tests as it is clear the TriG-1.1 compliance suite hasn't picked this up.

**Comment by ansell** [comment] 2016-07-22 00:28
The bug seems to be that you chose the name "graph" for the prefix. The keyword "GRAPH" (case-insensitive) probably may be rejected in TriG-1.1 as a prefix name because it is a reserved word inherited from SPARQL. On the other hand, I will try to find a way of parsing it before asking the W3C for their opinion as to whether it is a valid prefix in that context.

**Comment by RickMoynihan** [comment] 2016-07-22 09:59
@ansell Interesting, I completely missed that part of the spec.  I can confirm that other prefixes do indeed work.

I guess it makes sense to align with SPARQL syntax, though it's worth noting that this query appears to conform to the SPARQL grammar, as I understand it (and it seems to parse in sesame):

````sparql
PREFIX graph: <http://foo/> 

SELECT * WHERE { 
   GRAPH graph:bar { 
      ?s ?p ?o 
    }
}
````

Given this (and assuming the above is legal), and the implied alignment goal of TriG to a subset of SPARQL syntax, it seems to me that Trig should definitely parse this too, as erroring will lead to undesirable incompatibilities between prefixes and serialisations.

If the W3C say that a prefix of `graph` is reserved then it would obviously be better for the writer and parser to raise an error immediately rather than parsing it as null.

**Comment by jeenbroekstra** [comment] 2016-07-24 21:34
Merged fix provided by @ansell

**Closed by jeenbroekstra** 2016-07-24 21:34 UTC
Labels: bug
