### ISSUE TITLE
Placement of FROM statement not compatible with Virtuoso

### ISSUE THREAD

**Issue by reckart** [eclipse/rdf4j#1324] opened 2019-03-06 16:09 UTC
The `SparqlBuilder` places the `FROM` statement at the beginning of the query:

```
          FROM <http://dbpedia.org>
          SELECT DISTINCT ?s
          WHERE { { <http://dbpedia.org/ontology/Organisation> <http://www.w3.org/2000/01/rdf-schema#subClassOf>+ ?s . } UNION { <http://dbpedia.org/ontology/Organisation> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>/<http://www.w3.org/2000/01/rdf-schema#subClassOf>* ?s . }
          FILTER EXISTS { { ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2000/01/rdf-schema#Class> . } UNION { [ ] <http://www.w3.org/2000/01/rdf-schema#subClassOf> ?s . } UNION { ?s <http://www.w3.org/2000/01/rdf-schema#subClassOf> [ ] . } } }
          GROUP BY ?s
          LIMIT 1000
```

This is not compatible with Virtuoso as can be seen by running the above query on [DBPedia](https://dbpedia.org/sparql) (disable strict variable checking):

```
Virtuoso 37000 Error SP030: SPARQL compiler, line 3: syntax error at 'FROM' before '<http://dbpedia.org>'
```

Moving the `FROM` statement between the `SELECT` and the `WHERE` clause fixes the problem.

```
          SELECT DISTINCT ?s
          FROM <http://dbpedia.org>
          WHERE { { <http://dbpedia.org/ontology/Organisation> <http://www.w3.org/2000/01/rdf-schema#subClassOf>+ ?s . } UNION { <http://dbpedia.org/ontology/Organisation> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>/<http://www.w3.org/2000/01/rdf-schema#subClassOf>* ?s . }
          FILTER EXISTS { { ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2000/01/rdf-schema#Class> . } UNION { [ ] <http://www.w3.org/2000/01/rdf-schema#subClassOf> ?s . } UNION { ?s <http://www.w3.org/2000/01/rdf-schema#subClassOf> [ ] . } } }
          GROUP BY ?s
          LIMIT 1000
```

See also: http://docs.openlinksw.com/virtuoso/rdfdefaultgraph/

**Comment by barthanssens** [comment] 2019-03-06 18:26
Looks like a duplicate of #1245

**Comment by bbagnall** [comment] 2019-05-26 02:49
I've created #1427 to address this

**Closed** 2019-06-06 03:57 UTC
Labels: duplicate, sparqlbuilder, specification
