### ISSUE TITLE
Decouple RDF model interfaces to a dedicated maven module

### ISSUE THREAD

**Issue by knoan** [eclipse/rdf4j#2538] opened 2020-09-26 21:06 UTC
The interfaces defining the RDF abstract data model (`org.eclipse.rdf4j.model`) are currently bundled in the `rdf4j-model` maven module with their simple implementations and a number of supporting utilities, totalling some 425 kb when packaged in a jar file.

Decoupling them to a dedicated module without dependencies would make it easier to port third-party interoperable libraries to limited devices supporting for instance Web of Thing applications.

The operation can be carried out without breaking changes; if there is consensus, I can submit a PR: just let's agree the artifactId/name/description for the new abstract module and how to update current name/description for `rdf4j-model`.

**Comment by jeenbroekstra** [comment] 2020-09-27 23:15
`rdf4j-model-api` is a good name for the interface module, that follows the same pattern we also use for the repository and sail apis.

I would ideally like things split up even further, for example a separate 'rdf4j-vocabularies' module would be useful, but perhaps we should leave that out of scope for now. 

I would suggest _not_ including the classes and interfaces in package `org.eclipse.rdf4j` (IsolationLevel, RDF4JException etc) in the new api package. They should probably be moved to an rdf4j-common module at some point (again though, out of scope for this).

**Comment by knoan** [comment] 2020-09-28 12:19
Initial PR submited for review. I had to manage two unforeseen dependencies:

- `Triple` is annotated as `@Experimental`
  - migrated `org.eclipse.rdf4j.common.annotation` package to `rdf4j-model-api` module
  - seems to make sense (as long as other annotations are not added), as `@Experimental/@InternalUseOnly` relate mainly to APIs
- the default implementation of `Model.setNamespace(String prefix, String name)` created `SimpleNamespace` objects
  - replaced `SimpleNamespace` with lightweight  read-only package-local `BasicNamespace` implementation

Concerning the latter point I wonder if we should:

1. migrate `org.eclipse.rdf4j.model.impl` to the `rdf4j-model-api` module
   1. seems to negate the original goal of the proposal, especially when taking into account all of the specific implementation classes related to `Model`
2. leave `Model` in the `rdf4j-model` module
   1. splitting the `org.eclipse.rdf4j.model` package across multiple modules feels quite hacky
3. provide additional lightweight implementations of  `org.eclipse.rdf4j.model` interfaces, wherever feasible directly as default methods 
   1. generates some overlap with `org.eclipse.rdf4j.model.impl.Simple*` implementations
   2. on the plus side, would provide a self-contained model definition working out of the box

**Comment by knoan** [comment] 2020-09-28 13:50
Not sure how to fix the current build error:

> Error:  Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.14.3:cmp (default) on project rdf4j-util: There is at least one incompatibility: java.lang.annotation.Annotation[java.lang.annotation.Annotation]:INTERFACE_REMOVED,org.eclipse.rdf4j.common.annotation.Experimental:SUPERCLASS_REMOVED,org.eclipse.rdf4j.common.annotation.Experimental:CLASS_REMOVED,java.lang.annotation.Annotation[java.lang.annotation.Annotation]:INTERFACE_REMOVED,org.eclipse.rdf4j.common.annotation.InternalUseOnly:SUPERCLASS_REMOVED,org.eclipse.rdf4j.common.annotation.InternalUseOnly:CLASS_REMOVED -> [Help 1]
429

**Comment by jeenbroekstra** [comment] 2020-09-28 23:59
> Initial PR submited for review. I had to manage two unforeseen dependencies:
> 
>     * `Triple` is annotated as `@Experimental`
>       
>       * migrated `org.eclipse.rdf4j.common.annotation` package to `rdf4j-model-api` module
>       * seems to make sense (as long as other annotations are not added), as `@Experimental/@InternalUseOnly` relate mainly to APIs

Works for me. 

>     * the default implementation of `Model.setNamespace(String prefix, String name)` created `SimpleNamespace` objects
>       
>       * replaced `SimpleNamespace` with lightweight  read-only package-local `BasicNamespace` implementation

I'll look at that in the PR and comment there.

> Concerning the latter point I wonder if we should:
> 
>     1. migrate `org.eclipse.rdf4j.model.impl` to the `rdf4j-model-api` module
>        
>        1. seems to negate the original goal of the proposal, especially when taking into account all of the specific implementation classes related to `Model`
> 
>     2. leave `Model` in the `rdf4j-model` module
>        
>        1. splitting the `org.eclipse.rdf4j.model` package across multiple modules feels quite hacky
> 
>     3. provide additional lightweight implementations of  `org.eclipse.rdf4j.model` interfaces, wherever feasible directly as default methods
>        
>        1. generates some overlap with `org.eclipse.rdf4j.model.impl.Simple*` implementations, especially for proper handling of Literal value accessors (e.g. `calendarValue()`)
>        2. on the plus side, would provide a self-contained model definition working out of the box
> 
>     4. leave everything as is

My preference is go for migration of common functionality to the model-api module in the form of abstract base classes (similar to how the repository-api package has a `oer.repository.base` package with abstract classes), which we can refactor the Simple* implementations to inherit from. That gives you a good "by design" starting point for your own implementations, and any default methods in the API can be implemented by some anonymous, private or package-private concrete subclass of that.

**Comment by jeenbroekstra** [comment] 2020-09-29 01:07
As for the build failure: the fact that we are moving things from one module to another is picked up as a (binary) incompatible change, which is strictly spearking correct: it means that existing projects that previously included the rdf4j-model jar file will now _also_ need to include a new jar file to work, and if they don't, they'll start failing. 

Of course, that's what the maven dependency resolution mechanism is for, but plenty of uses of RDF4J exist that either just download jars manually, or use tools like maven or gradle but disable transitive dependencies, and all of those will start failing once they bump their RDF4J version.

Generally speaking, we try to guarantee binary compatibility where we can - this is why the japicmp plugin is configured to check binary compatibility. However, there's nothing to say that we _have_ to, for every release. Our general semver guarantee is that we are "backward compatible", which at a minimum means source compatibility (roughly speaking "I can recompile my existing code against the new version without having to change my code"), or at least binary compatible assuming you take care the necessary binaries are on the classpath. 

I'll adapt the configuration of the api comparison plugin so that it doesn't fail the build on this particular change, and push that to your branch. We will just have to make sure we are clear in the release notes that people need to make sure everything they need is still on their classpath.

**Comment by knoan** [comment] 2020-09-29 17:41
> My preference is go for migration of common functionality to the model-api module in the form of abstract base classes … which we can refactor the Simple* implementations to inherit from. 

Gone this way.

Before closing still to review factoring opportunities for `AbstracModel/AbstractValueFactory`.

**Comment by knoan** [comment] 2020-09-30 14:43
I completed the review of the remaining implementation classes in `oer.model.impl` without identifying further viable factoring opportunities.

 `AbstractModel` could be moved as is to `oer.model.base`, but preserving compatibility would mean leaving behing a bridge class, which is not probably worth the trouble. As an aside, during the review I identified a bug in `hashCode()`, which I reported separately as #2560.

Factoring  `AbstractValueFactory`  would cause extensive duplication of functionalities already included in `Simple*` values, which I'd rather avoid. Taking into account the stated goals of the PR, it's probably better having each host environment provide a custom `ValueFactory` with a suitable level of optimization.

**Comment by knoan** [comment] 2020-09-30 14:45
I'd also draw to your attention the last two commits:

**GH-2538 Patch regression at oer.sail.memory.MemoryRDFStarSupportTest** / Changing the definition of `AbstractTuple.hashCode()` to avoid incurring in the cost of an array creation per call breaks `MemoryRDFStarSupportTest.testAddRDFStarSubject()/Object()`. Just changing the hashing constant after inlining `Objects.hash(Object[])` has the very same effect, which is definetely not expected. Unable to trace the root cause :-(

**GH-2538 Patch regression at oer.sail.shacl.UniqueTest** / Including language and dataype in `AbstractLiteral.hashCode()`  breaks `oer.sail.shacl.UniqueTest.tupleCardinality2()`. The issue may be traced to `oer.sail.shacl.planNodes.Tuple.compareTo()`, which doesn't apparently correctly handle tuples of different length: shorter tuples should compare as lesser than longer ones, while in the current implementation they compare equal, leaving the sort unstable and sensitive to hash-induced ordering in `UniqueTest.runTest()` at:

```
ArrayList<Tuple> expected = new ArrayList<>(new HashSet<>(new MockConsumePlanNode(input).asList()));
```

**Comment by knoan** [comment] 2020-09-30 14:47
Thad said, from my point of view the PR can be considered complete, possibly after:

- defining the sharing strategy for the abstract value test suites
- reverting the last two patches once the underlying issues are resolved

Let me know how to wrap up.

**Comment by knoan** [comment] 2020-09-30 14:48
BTW Do we have a quick way of preventing `mvn process-resources` from altering config files under `.idea`?

**Comment by knoan** [comment] 2020-10-01 07:57
#2564 requires a complete revision of `.hashCode()` methods: I tried to streamline them, but the new implementations are at risk of breaking code in very nasty ways…

**Comment by jeenbroekstra** [comment] 2020-10-01 12:13
> BTW Do we have a quick way of preventing `mvn process-resources` from altering config files under `.idea`?

I'm not sure, I don't use IntelliJ myself. But this should not affect anything right? Are you experiencing problems? What kind of files is it touching that it should not?

**Closed** 2020-10-04 20:23 UTC
Labels: 📦 model, 📶 enhancement
