### ISSUE TITLE
Parsing Cell Line Ontology Failed because of ParsedIRI 

### ISSUE THREAD

**Issue by mannyrivera2010** [eclipse/rdf4j#2869] opened 2021-02-23 23:38 UTC
Parsing CLO owl file using RDFFormat.RDFXML fails

Ontology: `https://bioportal.bioontology.org/ontologies/CLO`

```
    <rdf:Description rdf:about="&obo;Matches%20in�27爋ntologies">
    </rdf:Description>
```

```
public class ExampleParsedIRI {

	public static void main(String[] args) throws URISyntaxException {
		System.out.println(new ParsedIRI("http://purl.obolibrary.org/obo/Matches%20in�27爋ntologies"));

//		Exception in thread "main" java.net.URISyntaxException: Unexpected character U+FFFD at index 43: http://purl.obolibrary.org/obo/Matches%20in�27爋ntologies
//		at org.eclipse.rdf4j.common.net.ParsedIRI.error(ParsedIRI.java:1034)
//		at org.eclipse.rdf4j.common.net.ParsedIRI.parse(ParsedIRI.java:815)
//		at org.eclipse.rdf4j.common.net.ParsedIRI.<init>(ParsedIRI.java:270)
//		at org.eclipse.rdf4j.examples.model.Example01BuildModel.main(Example01BuildModel.java:33)

	}
}
```

https://github.com/eclipse/rdf4j/blob/main/core/util/src/main/java/org/eclipse/rdf4j/common/net/ParsedIRI.java
Changing
```
private static int[][] fchar = union(pchar, '/', '?');
```
to 
```
private static int[][] fchar = union(pchar, '/', '?', '�');
````
fixed URISyntaxException

**Comment by jeenbroekstra** [comment] 2021-02-24 05:04
'�' (whatever that char is, it's hard to tell from the copy-paste here) is not a legal character in an IRI. This is not a bug that needs to be fixed in ParsedIRI, but in the source data. 

You can also choose to disable IRI validation in the parser: https://rdf4j.org/documentation/programming/rio/#example-iri-syntax-validation. Of course, you may still encounter problems further down the line with this.

**Comment by mannyrivera2010** [comment] 2021-02-24 05:40
Thank you for the advice

**Comment by jeenbroekstra** [comment] 2021-02-24 05:42
All good. Closing this now, but feel free to reach out again if you run into other issues.

**Closed by jeenbroekstra** 2021-02-24 05:42 UTC

**Comment by mannyrivera2010** [comment] 2021-02-24 06:15
I could see VERIFY_URI_SYNTAX in the turtle parser. Think it would be good if rdfxml parser could respect VERIFY_URI_SYNTAX setting

**Comment by jeenbroekstra** [comment] 2021-02-24 07:23
> I could see VERIFY_URI_SYNTAX in the turtle parser. Think it would be good if rdfxml parser could respect VERIFY_URI_SYNTAX setting also

It does. Give it a go.
