### ISSUE TITLE
QueryJoinOptimizer breaks ordering of dependent statements

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#83] opened 2016-05-11 07:15 UTC
(Migrated from https://openrdf.atlassian.net/browse/SES-2275 )

Test case bind03 passes by happy coincidence rather than by design (attached for convenience).
Currently, to evaluate
{code}
PREFIX : http://example.org/ 

SELECT ?z ?s1
{
  ?s ?p ?o .
  BIND(?o+1 AS ?z)
  ?s1 ?p1 ?z
}
{code}
depends on the order in which the statements are passed to the evaluation engine. But the QueryJoinOptimizer can rearrange the order. In this case, the order is unchanged, but the following fails:
{code}
PREFIX : http://example.org/ 

SELECT ?z ?s1
{
  ?s ?p ?o .
  BIND(?o+1 AS ?z)
  ?s1 :p ?z
}
{code}
whereas this works:
{code}
PREFIX : http://example.org/ 

SELECT ?z ?s1
{
  ?s :p ?o .
  BIND(?o+1 AS ?z)
  ?s1 ?p1 ?z
}
{code}
.
Should sparql be working out the dependency ordering or should it respect the ordering given by the user? i.e. should this work or not:
{code}
PREFIX : http://example.org/ 

SELECT ?z ?s1
{
  ?s1 ?p1 ?z
  BIND(?o+1 AS ?z)
  ?s :p ?o .
}
{code}

**Comment by jamesrdf** [comment] 2017-08-29 15:27
Duplicate of #380

**Closed by jamesrdf** 2017-08-29 15:27 UTC
Labels: bug, specification
