### ISSUE TITLE
Performance degrades with concurrent reads

### ISSUE THREAD

**Issue by MiguelAraCo** [eclipse/rdf4j#236] opened 2016-07-13 17:22 UTC
Performance degrades for all concurrent reads to the same repository.

As an example, concurrent actions that read all the statements of a repository take: 

**actions / time per action**

- 1 / 2.4s
- 4 / 4.9s
- 16 / 21.9s
- 64 / 87.6s

Code used to get these results can be cloned from here: https://github.com/MiguelAraCo/rdf4j-concurrency

Are these results normal? Is there a way to improve them? My last resort would be to implement an in memory cache system but I want to know what you guys think first.

Thanks :)

**Comment by jeenbroekstra** [comment] 2016-07-14 03:20
Although some degradation is to be expected, this looks excessive.

I haven't ran any tests yet but I think the problem may be caused by the store being over-enthusiastic in branching/forking its source data when starting a new transaction.

A possible workaround (or at least an experiment) is this: start an explicit new transaction for every query, but make sure you use IsolationLevel.NONE. See if that influences the performance figures significantly.

**Comment by MiguelAraCo** [comment] 2016-07-14 19:08
I'm getting the same results when doing it with an `IsolationLevels.None`. I also tried doing the reads without creating a transaction and the results are pretty much the same

**Comment by jeenbroekstra** [comment] 2016-07-14 22:49
I can reproduce the results. But I have been having a bit more of a think about the test and what it shows, and I think it is actually more or less normal (or at least not excessive), after all.

What we're seeing is that concurrent reads make each individual read action slow down, but the compound result is still less than if you had executed the reads sequentially. For example, using your results, sequentially executing 64 queries would have been 64 * 2.4 = 153.6 seconds, whereas the concurrent approach did it in a little over half that time.

The amount of degradation as number of concurrent threads goes up is highly influenced by the nature of the query that you're doing. Your benchmark is on the extreme end of the spectrum because you are retrieving _all_ statements in the store. The store does have some caching capabilities built in, but because your query effectively scans the entire database, those caches may not be helping much: cache entries are dropped again before a second thread has a chance to make use of them. 

The degradation goes down as your query is more focused and retrieves a smaller subset of data. As an extreme example of this, if you modify your read test to only retrieve statements about a single subject (in your dataset, the result is only a single triple), like so:

```
			BenchmarkTuple<Integer> benchmark = App.benchmark(() -> App.executeInTransaction(connection -> {

				IRI subject = connection.getValueFactory().createIRI("http://dbpedia.org/resource/Normandy");
				RepositoryResult<Statement> result = connection.getStatements(subject, null, null);
```

The results I get back when running this are much better (if more fluctuating, but that may because I'm just running this on my laptop which has a gazillion other things going on). Single thread performance is at ~1,000,000, 4 threads mean is at the same, 64 thread mean is at ~2,000,000 (I'm assuming these are nanoseconds btw?)

All in all I'd say that what you're measuring is worst-case performance, and practical concurrent access will behave much better, because not every concurrent read will be a sequential scan of the database (unless you have a _very_ strange use case :))

**Comment by MiguelAraCo** [comment] 2016-07-15 14:55
Thanks for taking the time to reproduce the results :). You are right, my test is basically the worst case scenario (although maybe the worst case would be reads in the middle of write access?). 

I'll keep doing some tests, but at the end if this performance is to be expected I may end up implementing some sort of in memory cache system. Maybe use the MemoryStore as a cache for heavily accessed triples? Any thoughts?

Again, thank you for your support.

**Comment by jeenbroekstra** [comment] 2016-07-19 00:54
It's possible, though getting the details of this might be trickier than you anticipate - and given that the native store already does quite a bit of low-level caching itself, it may not be obvious to improve it. 

But if you're confident you want to build it, consider contributing your effort back to the project - that way we can review your work and give you feedback, and of course it might be useful for others too!

**Comment by jeenbroekstra** [comment] 2016-07-21 22:06
Closing this issue as I think we established the cause and it's not something we can easily do anything about. Any suggested improvement should probably be logged as a new issue.

**Closed by jeenbroekstra** 2016-07-21 22:06 UTC
