### ISSUE TITLE
FedX Query Does Not Apply Dataset

### ISSUE THREAD

**Issue by daltontc** [eclipse/rdf4j#4295] opened 2022-11-29 20:22 UTC
### Current Behavior

FedX TupleQueries do not apply the dataset when evaluating, returning results outside the dataset. I assume this same behavior is happening for other types of queries as well.

See https://github.com/daltontc/rdf4jTest/tree/bug/fedx_dataset for an example.

### Expected Behavior

FedX queries will properly filter results using the supplied Dataset.

### Steps To Reproduce

Clone https://github.com/daltontc/rdf4jTest/tree/bug/fedx_dataset and Run Main.java

```
import org.apache.commons.io.FileUtils;
import org.apache.commons.lang3.time.StopWatch;
import org.eclipse.rdf4j.federated.FedXFactory;
import org.eclipse.rdf4j.federated.endpoint.Endpoint;
import org.eclipse.rdf4j.federated.endpoint.EndpointFactory;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Model;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.Binding;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.Dataset;
import org.eclipse.rdf4j.query.TupleQuery;
import org.eclipse.rdf4j.query.TupleQueryResult;
import org.eclipse.rdf4j.query.impl.SimpleDataset;
import org.eclipse.rdf4j.repository.Repository;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.rio.RDFFormat;
import org.eclipse.rdf4j.rio.Rio;
import org.eclipse.rdf4j.sail.memory.MemoryStore;
import org.eclipse.rdf4j.sail.nativerdf.NativeStore;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class Main {
    static ValueFactory vf = SimpleValueFactory.getInstance();

    public static void main(String[] args) throws IOException {
        IRI context = vf.createIRI("https://test.com/context");
        Path path = Paths.get("target/test");
        if (Files.exists(path)) {
            System.out.println("Deleting old repo");
            FileUtils.deleteDirectory(path.toFile());
        }

        NativeStore store = new NativeStore();
        store.setTripleIndexes("spoc,posc,cspo,opsc");
        store.setDataDir(path.toFile());
        Repository repo = new SailRepository(store);
        repo.init();
        try (RepositoryConnection conn = repo.getConnection()) {
            System.out.println("Loading in data");
            InputStream is = Main.class.getResourceAsStream("/test.trig");
            Model model = Rio.parse(is, "", RDFFormat.TRIG);
            conn.add(model);
            System.out.println("Loading in data COMPLETE");
        }
        repo.shutDown();

        List<Endpoint> endpoints = new ArrayList<>();
        endpoints.add(EndpointFactory.loadNativeEndpoint(store.getDataDir()));
        Repository fedXRepo = FedXFactory.createFederation(endpoints);

        try (RepositoryConnection conn = fedXRepo.getConnection()) {
            TupleQuery query = conn.prepareTupleQuery("select * where {?s ?p ?o} limit 10");
            SimpleDataset dataset = new SimpleDataset();
            dataset.addDefaultGraph(vf.createIRI("http://mobi.com/dataset/d62947b8-b957-49fa-b46a-97c26cf9d7d7_system_dng"));
            query.setDataset(dataset);

            System.out.println("Dataset: " + query.getDataset());

            // Outputs values not from the dataset
            TupleQueryResult result = query.evaluate();
            for (BindingSet solution : result) {
                System.out.println("?s = " + solution.getValue("s") + "\t" + "?p = " + solution.getValue("p") + "\t" + "?o = " + solution.getValue("o"));
            }
        }
    }
}
```

test.trig
```
<http://mobi.com/policies/dataset-creation> {
  <http://mobi.com/policies/dataset-creation> a <http://www.w3.org/2002/07/owl#Thing>,
      <http://mobi.com/ontologies/policy#PolicyFile>, <http://mobi.com/ontologies/policy#Policy>,
      <http://mobi.com/ontologies/documents#BinaryFile>;
    <http://mobi.com/ontologies/documents#retrievalURL> <file:///Users/tom/workspace/mobi/mobi-distribution/target/mobi-distribution-2.1.0-SNAPSHOT/data/virtualFiles/policies/fb/e1/ff138c7f76e1>;
    <http://mobi.com/ontologies/documents#size> 4.077E3;
    <http://mobi.com/ontologies/documents#fileName> "file:///Users/tom/workspace/mobi/mobi-distribution/target/mobi-distribution-2.1.0-SNAPSHOT/data/virtualFiles/policies/fb/e1/ff138c7f76e1.xml";
    <http://mobi.com/ontologies/documents#checksum> """\\^�tu����f�&	�Ls�vJy.p��0a揋""";
    <http://mobi.com/ontologies/policy#relatedResource> <http://mobi.com/catalog-local>;
    <http://mobi.com/ontologies/policy#relatedAction> <http://mobi.com/ontologies/policy#Create> .
}

<http://mobi.com/policies/record/https%3A%2F%2Fmobi.com%2Frecords%231b18ced2-0496-40db-af10-374f489ae4ce> {
  <http://mobi.com/policies/record/https%3A%2F%2Fmobi.com%2Frecords%231b18ced2-0496-40db-af10-374f489ae4ce>
    a <http://www.w3.org/2002/07/owl#Thing>, <http://mobi.com/ontologies/policy#PolicyFile>,
      <http://mobi.com/ontologies/policy#Policy>, <http://mobi.com/ontologies/documents#BinaryFile>;
    <http://mobi.com/ontologies/documents#retrievalURL> <file:///Users/tom/workspace/mobi/mobi-distribution/target/mobi-distribution-2.1.0-SNAPSHOT/data/virtualFiles/policies/d8/98/d73e825a32a5>;
    <http://mobi.com/ontologies/documents#size> 6.857E3;
    <http://mobi.com/ontologies/documents#fileName> "file:///Users/tom/workspace/mobi/mobi-distribution/target/mobi-distribution-2.1.0-SNAPSHOT/data/virtualFiles/policies/d8/98/d73e825a32a5.xml";
    <http://mobi.com/ontologies/documents#checksum> """BN�U
'�!Q�n��)ι�<�;���kDz""";
    <http://mobi.com/ontologies/policy#relatedResource> <https://mobi.com/records#1b18ced2-0496-40db-af10-374f489ae4ce> .
}

<http://mobi.com/dataset/d62947b8-b957-49fa-b46a-97c26cf9d7d7_system_dng> {
  <http://mobi.com/data/uhtc/crystalstructure/Hexagonal> a <http://matonto.org/ontologies/uhtc#CrystalStructure>;
    <http://www.w3.org/2000/01/rdf-schema#label> "Hexagonal";
    <http://matonto.org/ontologies/uhtc#crystalStructureName> "Hexagonal" .

  <http://mobi.com/data/uhtc/crystalstructure/Polymorphic> a <http://matonto.org/ontologies/uhtc#CrystalStructure>;
    <http://www.w3.org/2000/01/rdf-schema#label> "Polymorphic";
    <http://matonto.org/ontologies/uhtc#crystalStructureName> "Polymorphic" .

  <http://mobi.com/data/uhtc/material/HfB2> a <http://matonto.org/ontologies/uhtc#Material>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Hafnium diboride is an ultrahigh temperature ceramic composed of hafnium and boron. It has a melting temperature of about 3250 degrees Celsius. It is an unusual ceramic, having relatively high thermal and electrical conductivities, properties it shares with isostructural titanium diborideæandæzirconium diboride. It is a grey, metallic looking material. Hafnium diboride has a hexagonalæcrystalæstructure, aæmolar massæof 200.11 grams per mole, and a density of 10.5 grams per cubic centimeter.";
    <http://www.w3.org/2000/01/rdf-schema#label> "HfB2";
    <http://matonto.org/ontologies/uhtc#chemicalFormula> "HfB2";
    <http://matonto.org/ontologies/uhtc#crystalStructure> <http://mobi.com/data/uhtc/crystalstructure/Hexagonal>;
    <http://matonto.org/ontologies/uhtc#density> 1.119E1;
    <http://matonto.org/ontologies/uhtc#element> <http://mobi.com/data/uhtc/element/Boron>,
      <http://mobi.com/data/uhtc/element/Hafnium>;
    <http://matonto.org/ontologies/uhtc#meltingPoint> 3.38E3 .

  <http://mobi.com/data/uhtc/element/Boron> a <http://matonto.org/ontologies/uhtc#Element>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Boron is a chemical element with symbol B and atomic number 5. Produced entirely by cosmic ray spallation and supernovae and not by stellar nucleosynthesis, it is a low-abundance element in the Solar system and in the Earth's crust.";
    <http://www.w3.org/2000/01/rdf-schema#label> "Boron";
    <http://matonto.org/ontologies/uhtc#elementName> "Boron";
    <http://matonto.org/ontologies/uhtc#symbol> "B" .

  <http://mobi.com/data/uhtc/element/Hafnium> a <http://matonto.org/ontologies/uhtc#Element>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Hafnium is a chemical element with symbol Hf and atomic number 72. A lustrous, silvery gray, tetravalent transition metal, hafnium chemically resembles zirconium and is found in many zirconium minerals.";
    <http://www.w3.org/2000/01/rdf-schema#label> "Hafnium";
    <http://matonto.org/ontologies/uhtc#elementName> "Hafnium";
    <http://matonto.org/ontologies/uhtc#symbol> "Hf" .

  <http://mobi.com/data/uhtc/material/HfC> a <http://matonto.org/ontologies/uhtc#Material>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Hafnium carbide is a chemical compound of hafnium and carbon. With a melting point of about 3900 C it is one of the most refractory binary compounds known.";
    <http://www.w3.org/2000/01/rdf-schema#label> "HfC";
    <http://matonto.org/ontologies/uhtc#chemicalFormula> "HfC";
    <http://matonto.org/ontologies/uhtc#crystalStructure> <http://mobi.com/data/uhtc/crystalstructure/FCC>;
    <http://matonto.org/ontologies/uhtc#density> 1.276E1;
    <http://matonto.org/ontologies/uhtc#element> <http://mobi.com/data/uhtc/element/Hafnium>,
      <http://mobi.com/data/uhtc/element/Carbon>;
    <http://matonto.org/ontologies/uhtc#meltingPoint> 3.9E3 .

  <http://mobi.com/data/uhtc/element/Carbon> a <http://matonto.org/ontologies/uhtc#Element>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Carbon (from Latin: carbo \"coal\") is a chemical element with symbol C and atomic number 6. It is nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds. Three isotopes occur naturally, 12C and 13C being stable, while 14C is a radioactive isotope, decaying with a half-life of about 5,730 years.[14] Carbon is one of the few elements known since antiquity.";
    <http://www.w3.org/2000/01/rdf-schema#label> "Carbon";
    <http://matonto.org/ontologies/uhtc#elementName> "Carbon";
    <http://matonto.org/ontologies/uhtc#symbol> "C" .

  <http://mobi.com/data/uhtc/material/HfN> a <http://matonto.org/ontologies/uhtc#Material>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Hafnium Nitride is an ultrahigh temperature ceramic composed of hafnium and boron.";
    <http://www.w3.org/2000/01/rdf-schema#label> "HfN";
    <http://matonto.org/ontologies/uhtc#chemicalFormula> "HfN";
    <http://matonto.org/ontologies/uhtc#crystalStructure> <http://mobi.com/data/uhtc/crystalstructure/FCC>;
    <http://matonto.org/ontologies/uhtc#density> 1.39E1;
    <http://matonto.org/ontologies/uhtc#element> <http://mobi.com/data/uhtc/element/Hafnium>,
      <http://mobi.com/data/uhtc/element/Nitrogen>;
    <http://matonto.org/ontologies/uhtc#meltingPoint> 3.385E3 .

  <http://mobi.com/data/uhtc/element/Nitrogen> a <http://matonto.org/ontologies/uhtc#Element>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Nitrogen is a chemical element with symbol N and atomic number 7. It was first discovered and isolated by Scottish physician Daniel Rutherford in 1772.";
    <http://www.w3.org/2000/01/rdf-schema#label> "Nitrogen";
    <http://matonto.org/ontologies/uhtc#elementName> "Nitrogen";
    <http://matonto.org/ontologies/uhtc#symbol> "N" .

  <http://mobi.com/data/uhtc/material/SiC> a <http://matonto.org/ontologies/uhtc#Material>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Silicon carbide, also known as carborundum, is a compound of silicon and carbon with chemical formula SiC. It occurs in nature as the extremely rare mineral moissanite.";
    <http://www.w3.org/2000/01/rdf-schema#label> "SiC";
    <http://matonto.org/ontologies/uhtc#chemicalFormula> "SiC";
    <http://matonto.org/ontologies/uhtc#crystalStructure> <http://mobi.com/data/uhtc/crystalstructure/Polymorphic>;
    <http://matonto.org/ontologies/uhtc#density> 3.21E0;
    <http://matonto.org/ontologies/uhtc#element> <http://mobi.com/data/uhtc/element/Carbon>,
      <http://mobi.com/data/uhtc/element/Silicon>;
    <http://matonto.org/ontologies/uhtc#meltingPoint> 2.82E3 .

  <http://mobi.com/data/uhtc/element/Silicon> a <http://matonto.org/ontologies/uhtc#Element>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Silicon is a chemical element with symbol Si and atomic number 14. A hard and brittle crystalline solid with a blue-gray metallic luster, it is a tetravalent metalloid.";
    <http://www.w3.org/2000/01/rdf-schema#label> "Silicon";
    <http://matonto.org/ontologies/uhtc#elementName> "Silicon";
    <http://matonto.org/ontologies/uhtc#symbol> "Si" .

  <http://mobi.com/data/uhtc/material/TaB2> a <http://matonto.org/ontologies/uhtc#Material>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Tantalum borides are compounds of tantalum and boron most remarkable for their extreme hardness.";
    <http://www.w3.org/2000/01/rdf-schema#label> "TaB2";
    <http://matonto.org/ontologies/uhtc#chemicalFormula> "TaB2";
    <http://matonto.org/ontologies/uhtc#crystalStructure> <http://mobi.com/data/uhtc/crystalstructure/Hexagonal>;
    <http://matonto.org/ontologies/uhtc#density> 1.254E1;
    <http://matonto.org/ontologies/uhtc#element> <http://mobi.com/data/uhtc/element/Boron>,
      <http://mobi.com/data/uhtc/element/Tantalum>;
    <http://matonto.org/ontologies/uhtc#meltingPoint> 3.04E3 .

  <http://mobi.com/data/uhtc/element/Tantalum> a <http://matonto.org/ontologies/uhtc#Element>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Tantalum is a chemical element with symbol Ta and atomic number 73. Previously known as tantalium, its name comes from Tantalus, a villain from Greek mythology.";
    <http://www.w3.org/2000/01/rdf-schema#label> "Tantalum";
    <http://matonto.org/ontologies/uhtc#elementName> "Tantalum";
    <http://matonto.org/ontologies/uhtc#symbol> "Ta" .

  <http://mobi.com/data/uhtc/material/TaC> a <http://matonto.org/ontologies/uhtc#Material>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Tantalum carbides form a family of binary chemical compounds of tantalum and carbon with the empirical formula TaC_, where x usually varies between 0.4 and 1.";
    <http://www.w3.org/2000/01/rdf-schema#label> "TaC";
    <http://matonto.org/ontologies/uhtc#chemicalFormula> "TaC";
    <http://matonto.org/ontologies/uhtc#crystalStructure> <http://mobi.com/data/uhtc/crystalstructure/Cubic>;
    <http://matonto.org/ontologies/uhtc#density> 1.45E1;
    <http://matonto.org/ontologies/uhtc#element> <http://mobi.com/data/uhtc/element/Carbon>,
      <http://mobi.com/data/uhtc/element/Tantalum>;
    <http://matonto.org/ontologies/uhtc#meltingPoint> 3.8E3 .

  <http://mobi.com/data/uhtc/material/TaN> a <http://matonto.org/ontologies/uhtc#Material>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Tantalum nitride is an inorganic chemical compound. It is sometimes used to create barrier or \"glue\" layers between copper, or other conductive metals, and dielectric insulator films such as thermal oxides.";
    <http://www.w3.org/2000/01/rdf-schema#label> "TaN";
    <http://matonto.org/ontologies/uhtc#chemicalFormula> "TaN";
    <http://matonto.org/ontologies/uhtc#crystalStructure> <http://mobi.com/data/uhtc/crystalstructure/Cubic>;
    <http://matonto.org/ontologies/uhtc#density> 1.43E1;
    <http://matonto.org/ontologies/uhtc#element> <http://mobi.com/data/uhtc/element/Nitrogen>,
      <http://mobi.com/data/uhtc/element/Tantalum>;
    <http://matonto.org/ontologies/uhtc#meltingPoint> 2.7E3 .

  <http://mobi.com/data/uhtc/material/TiB2> a <http://matonto.org/ontologies/uhtc#Material>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Titanium diboride is an extremely hard ceramic which has excellent heat conductivity, oxidation stability and resistance to mechanical erosion.";
    <http://www.w3.org/2000/01/rdf-schema#label> "TiB2";
    <http://matonto.org/ontologies/uhtc#chemicalFormula> "TiB2";
    <http://matonto.org/ontologies/uhtc#crystalStructure> <http://mobi.com/data/uhtc/crystalstructure/Hexagonal>;
    <http://matonto.org/ontologies/uhtc#density> 4.52E0;
    <http://matonto.org/ontologies/uhtc#element> <http://mobi.com/data/uhtc/element/Boron>,
      <http://mobi.com/data/uhtc/element/Titanium>;
    <http://matonto.org/ontologies/uhtc#meltingPoint> 3.225E3 .

  <http://mobi.com/data/uhtc/element/Titanium> a <http://matonto.org/ontologies/uhtc#Element>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Titanium is a chemical element with symbol Ti and atomic number 22. It is a lustrous transition metal with a silver color, low density, and high strength. Titanium is resistant to corrosion in sea water, aqua regia, and chlorine.";
    <http://www.w3.org/2000/01/rdf-schema#label> "Titanium";
    <http://matonto.org/ontologies/uhtc#elementName> "Titanium";
    <http://matonto.org/ontologies/uhtc#symbol> "Ti" .

  <http://mobi.com/data/uhtc/material/TiC> a <http://matonto.org/ontologies/uhtc#Material>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Titanium carbide, TiC, is an extremely hard refractory ceramic material, similar to tungsten carbide. It has the appearance of black powder with the sodium chloride crystal structure. As found in nature its crystals range in size from 0.1 to 0.3mm.";
    <http://www.w3.org/2000/01/rdf-schema#label> "TiC";
    <http://matonto.org/ontologies/uhtc#chemicalFormula> "TiC";
    <http://matonto.org/ontologies/uhtc#crystalStructure> <http://mobi.com/data/uhtc/crystalstructure/Cubic>;
    <http://matonto.org/ontologies/uhtc#density> 4.94E0;
    <http://matonto.org/ontologies/uhtc#element> <http://mobi.com/data/uhtc/element/Carbon>,
      <http://mobi.com/data/uhtc/element/Titanium>;
    <http://matonto.org/ontologies/uhtc#meltingPoint> 3.1E3 .

  <http://mobi.com/data/uhtc/material/TiN> a <http://matonto.org/ontologies/uhtc#Material>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Titanium nitride is an extremely hard ceramic material, often used as a coating on titanium alloys, steel, carbide, and aluminium components to improve the substrate's surface properties.";
    <http://www.w3.org/2000/01/rdf-schema#label> "TiN";
    <http://matonto.org/ontologies/uhtc#chemicalFormula> "TiN";
    <http://matonto.org/ontologies/uhtc#crystalStructure> <http://mobi.com/data/uhtc/crystalstructure/FCC>;
    <http://matonto.org/ontologies/uhtc#density> 5.39E0;
    <http://matonto.org/ontologies/uhtc#element> <http://mobi.com/data/uhtc/element/Nitrogen>,
      <http://mobi.com/data/uhtc/element/Titanium>;
    <http://matonto.org/ontologies/uhtc#meltingPoint> 2.95E3 .

  <http://mobi.com/data/uhtc/material/ZrB2> a <http://matonto.org/ontologies/uhtc#Material>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Zirconium diboride is a highly covalent refractory ceramic material with a hexagonal crystal structure. ZrB is an ultra high temperature ceramic with a melting point of 3246 C.";
    <http://www.w3.org/2000/01/rdf-schema#label> "ZrB2";
    <http://matonto.org/ontologies/uhtc#chemicalFormula> "ZrB2";
    <http://matonto.org/ontologies/uhtc#crystalStructure> <http://mobi.com/data/uhtc/crystalstructure/Hexagonal>;
    <http://matonto.org/ontologies/uhtc#density> 6.1E0;
    <http://matonto.org/ontologies/uhtc#element> <http://mobi.com/data/uhtc/element/Boron>,
      <http://mobi.com/data/uhtc/element/Zirconium>;
    <http://matonto.org/ontologies/uhtc#meltingPoint> 3.245E3 .

  <http://mobi.com/data/uhtc/element/Zirconium> a <http://matonto.org/ontologies/uhtc#Element>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Zirconium is a chemical element with symbol Zr and atomic number 40. The name zirconium is taken from the name of the mineral zircon, the most important source of zirconium.";
    <http://www.w3.org/2000/01/rdf-schema#label> "Zirconium";
    <http://matonto.org/ontologies/uhtc#elementName> "Zirconium";
    <http://matonto.org/ontologies/uhtc#symbol> "Zr" .

  <http://mobi.com/data/uhtc/material/ZrC> a <http://matonto.org/ontologies/uhtc#Material>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Zirconium carbide is an extremely hard refractory ceramic material, commercially used in tool bits for cutting tools. It is usually processed by sintering.";
    <http://www.w3.org/2000/01/rdf-schema#label> "ZrC";
    <http://matonto.org/ontologies/uhtc#chemicalFormula> "ZrC";
    <http://matonto.org/ontologies/uhtc#crystalStructure> <http://mobi.com/data/uhtc/crystalstructure/FCC>;
    <http://matonto.org/ontologies/uhtc#density> 6.56E0;
    <http://matonto.org/ontologies/uhtc#element> <http://mobi.com/data/uhtc/element/Carbon>,
      <http://mobi.com/data/uhtc/element/Zirconium>;
    <http://matonto.org/ontologies/uhtc#meltingPoint> 3.4E3 .

  <http://mobi.com/data/uhtc/material/ZrN> a <http://matonto.org/ontologies/uhtc#Material>;
    <http://www.w3.org/2000/01/rdf-schema#comment> "Zirconium nitride is an inorganic compound used in a variety of ways due to its properties.";
    <http://www.w3.org/2000/01/rdf-schema#label> "ZrN";
    <http://matonto.org/ontologies/uhtc#chemicalFormula> "ZrN";
    <http://matonto.org/ontologies/uhtc#crystalStructure> <http://mobi.com/data/uhtc/crystalstructure/FCC>;
    <http://matonto.org/ontologies/uhtc#density> 7.29E0;
    <http://matonto.org/ontologies/uhtc#element> <http://mobi.com/data/uhtc/element/Nitrogen>,
      <http://mobi.com/data/uhtc/element/Zirconium>;
    <http://matonto.org/ontologies/uhtc#meltingPoint> 2.95E3 .
}
```

### Version

4.2.1

### Are you interested in contributing a solution yourself?

Perhaps?

**Comment by daltontc** [comment] 2022-11-29 20:25
Results from outside the dataset

```
Dataset: FROM <http://mobi.com/dat..-b46a-97c26cf9d7d7_system_dng>

?s = http://mobi.com/policies/dataset-creation	?p = http://www.w3.org/1999/02/22-rdf-syntax-ns#type	?o = http://www.w3.org/2002/07/owl#Thing
?s = http://mobi.com/policies/dataset-creation	?p = http://www.w3.org/1999/02/22-rdf-syntax-ns#type	?o = http://mobi.com/ontologies/policy#PolicyFile
?s = http://mobi.com/policies/dataset-creation	?p = http://www.w3.org/1999/02/22-rdf-syntax-ns#type	?o = http://mobi.com/ontologies/policy#Policy
?s = http://mobi.com/policies/dataset-creation	?p = http://www.w3.org/1999/02/22-rdf-syntax-ns#type	?o = http://mobi.com/ontologies/documents#BinaryFile
?s = http://mobi.com/policies/dataset-creation	?p = http://mobi.com/ontologies/documents#retrievalURL	?o = file:///Users/tom/workspace/mobi/mobi-distribution/target/mobi-distribution-2.1.0-SNAPSHOT/data/virtualFiles/policies/fb/e1/ff138c7f76e1
?s = http://mobi.com/policies/dataset-creation	?p = http://mobi.com/ontologies/documents#size	?o = "4.077E3"^^<http://www.w3.org/2001/XMLSchema#double>
?s = http://mobi.com/policies/dataset-creation	?p = http://mobi.com/ontologies/documents#fileName	?o = "file:///Users/tom/workspace/mobi/mobi-distribution/target/mobi-distribution-2.1.0-SNAPSHOT/data/virtualFiles/policies/fb/e1/ff138c7f76e1.xml"
?s = http://mobi.com/policies/dataset-creation	?p = http://mobi.com/ontologies/documents#checksum	?o = "\^�tu����f�&	�Ls�vJy.p��0a揋"
?s = http://mobi.com/policies/dataset-creation	?p = http://mobi.com/ontologies/policy#relatedResource	?o = http://mobi.com/catalog-local
?s = http://mobi.com/policies/dataset-creation	?p = http://mobi.com/ontologies/policy#relatedAction	?o = http://mobi.com/ontologies/policy#Create
```

The setter method is applying the dataset to the delegate and returning with the getter, but does not actually apply it to the query evaluation.


![image](https://user-images.githubusercontent.com/39524502/204640227-08bf9ad2-d3c5-4725-9da8-4492c9ce165c.png)

**Comment by hmottestad** [comment] 2022-11-30 06:01
Funky. Nice catch! 

Is it limited to FedX or have you managed to reproduce the bug directly with the NativeStore or the through the HTTPRepositoryConnection?

**Comment by JervenBolleman** [comment] 2022-12-14 20:40
I think the issue is in the class `TripleSourceBase::getStatements()` method where new queries are made but no dataset is passed in, or maybe  because the Dataset is not a FedXDataset?  @aschwarte10 what do you think?

**Comment by JervenBolleman** [comment] 2022-12-16 11:51
@daltontc I believe the issue is now resolved. Could you double check and let me know.

**Comment by daltontc** [comment] 2022-12-19 15:57
@JervenBolleman Just tested it against my test project. Things look great!!! Thanks!

**Comment by JervenBolleman** [comment] 2022-12-19 15:58
@daltontc thank you for the bug report. I am closing the issue now.

**Closed by JervenBolleman** 2022-12-19 15:58 UTC
Labels: 🐞 bug
