### ISSUE TITLE
Regression in hashCode vs equals for AbstractBindingSet

### ISSUE THREAD

**Issue by avataar** [eclipse/rdf4j#676] opened 2016-11-29 11:54 UTC
In 2.0.2 hashCode() and equals() were consistent for AbstractBindingSet (and thus all of its descendants) but in 2.0.3 hashCode() suddenly began to be sensitive to the order bindings are added, while equals() stayed agnostic to the order. As this is a Set I believe both hashCode() and equals() shouldn't care about the order and it's a good idea to keep them consistent either way.

This change was introduced by https://github.com/eclipse/rdf4j/pull/650.

**Comment by ansell** [comment] 2016-11-29 22:01
This may have been fixed by a recent PR: https://github.com/eclipse/rdf4j/pull/670

**Comment by jeenbroekstra** [comment] 2016-11-29 23:21
@ansell actually it isn't, because I forgot to revert the change to AbstractBindingSet - I only reverted the Literal hashcode change. 

@avataar do you have a simple test case that demonstrates the problem? Would be good to add a unit test to check for future regression.

**Comment by jeenbroekstra** [comment] 2016-11-29 23:45
I also note that, analogous to the (now reverted) change to literal, this change breaks our own API spec. `BindingSet.hashCode` has the following javadoc:

	/**
	 * The hash code of a binding is defined as the bit-wise XOR of the hash codes of its bindings:
	 * 
	 * <pre>
	 * int hashCode = 0;
	 *
	 * for (Binding binding : this) {
	 * 	hashCode &circ;= binding.getName().hashCode() &circ; binding.getValue().hashCode();
	 * }
	 * </pre>
	 * 
	 * Note: the calculated hash code intentionally does not depend on the order in which the bindings are
	 * iterated over.
	 * 
	 * @return A hash code for the BindingSet.
	 */

Not too happy with showing actual code in the javadoc tbh, but it's pretty clear that the changed impl violates this.

**Comment by jeenbroekstra** [comment] 2016-11-30 00:02
Having a look at adding regression tests for the various BindingSet impls now.

**Comment by ansell** [comment] 2016-11-30 00:06
In my view, it isn't necessary in the long term to define the hashcode algorithm, as it encourages users to expect the result to be constant which doesn't allow for improvements in future to better distribute the hashcodes. It also encourages them to erroneously think that they can use hashcode as an alternative to equals for equality. Ie, ```object1.hashcode == object2.hashcode``` has no significance at all if ```!object1.equals(object2)```.

I am fine with removing the algorithm from the API javadoc in a minor version release.

**Comment by jeenbroekstra** [comment] 2016-11-30 00:37
Pull Request up for review.

**Comment by jeenbroekstra** [comment] 2016-11-30 21:15
Thanks @avataar . Have a look at the PR, which contains tests and a fix.

**Closed** 2016-12-01 02:34 UTC
Labels: bug
