### ISSUE TITLE
Remove dependency to javax.xml.bind from core libraries

### ISSUE THREAD

**Issue by jetztgradnet** [eclipse/rdf4j#4421] opened 2023-02-13 09:35 UTC
### Problem description

We are in process of moving our application to JakartaEE and Jetty11. One blocker is the use of `javax.xml.bind` in the RDF4J core libraries (we do not use the workbench or server parts of RDF4J). 

A full move to JakartaEE is a huge topic (see #3559 and the WIP PR #4367) and staying compatible with both JavaEE and JakartaEE at the same time impossible or at least very difficult with additional variants.

We are looking for a minimal short-term solution in the 4.2.x/4.3 timeframe within the next few weeks.

### Preferred solution

We would like to get rid of the few uses of `javax.xml.bind` in the core libraries.

There are currently only 3 uses of `javax.xml.bind`:
* `org.eclipse.rdf4j.rio.helpers.AbstractRDFParser` uses `javax.xml.bind.annotation.adapters.HexBinaryAdapter` which (here) is a thin wrapper around `javax.xml.bind.DatatypeConverter.printHexBinary(byte[])`
* `org.eclipse.rdf4j.http.protocol.transaction.TransactionSAXParser` uses `javax.xml.bind.DatatypeConverter.parseBase64Binary(String)` (fully qualified class reference in line 96, not using an import)
* `org.eclipse.rdf4j.http.protocol.transaction.TransactionWriter` uses `javax.xml.bind.DatatypeConverter.printBase64Binary(byte[])`

Example of an exception at runtime (also see #3559):
```
java.lang.NoClassDefFoundError: javax/xml/bind/annotation/adapters/HexBinaryAdapter
	at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.createNode(AbstractRDFParser.java:413)
	at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser.createNode(RDFXMLParser.java:802)
	at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser.getNodeResource(RDFXMLParser.java:514)
	at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser.processNodeElt(RDFXMLParser.java:414)
	at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser.startElement(RDFXMLParser.java:331)
	at org.eclipse.rdf4j.rio.rdfxml.SAXFilter.reportDeferredStartElement(SAXFilter.java:303)
	at org.eclipse.rdf4j.rio.rdfxml.SAXFilter.startElement(SAXFilter.java:234)
```

The actual code in the respective methods of the default implementation (`javax.xml.bind.DatatypeConverterImpl`) is rather short, so maybe we can inline that in an equivalent way (although we would likely not be able to simply copy the original code as-is depending on the license...)

### Are you interested in contributing a solution yourself?

Perhaps?

**Comment by aschwarte10** [comment] 2023-02-13 09:51
Thanks @jetztgradnet for writing this up and extracting this specific aspect of Jakarta EE migration into its own issue.

I want to confirm that this aspect of Java XML Bind in some of the core libraries of RDF4J is blocking us in making steps in our migration. My assumption is that also other users of RDF4J will shortly run into this - as we currently observe shifts to the Jakarta EE eco-system all across the Java projects (specifically also the big open source drivers like Spring Boot).

@hmottestad , @abrokenjester : do you see that we can make a step here in a rather short-term release (for us also a milestone build would suffice with an appropriate timeline for the proper release)

**Comment by jetztgradnet** [comment] 2023-02-13 09:56
One possibility would be to create a `DatatypeConverterUtil` class which is used instead of the three uses and abstracts the calls to `javax.xml.bind.DatatypeConverter`. We could then wrap those calls and use (one-time) reflection to delegate this to either `javax.xml.bind.DatatypeConverter` or `jakarta.xml.bind.DatatypeConverter`. That way it would work with both variants. 
Note that this requires handling dependencies specifically. We simply use RDF4J without transitive dependencies and manage all dependencies explicitly, so this would work for us.

As @aschwarte10 pointed out above, this might be an initial step on the longer migration path to JakartaEE, but will already help everybody who uses RDF4J without the server parts.

**Comment by aschwarte10** [comment] 2023-02-20 08:16
PR https://github.com/eclipse/rdf4j/issues/4421 is now merged, the issue is resolved. 

Note that @jetztgradnet has also done validation with a local snapshpt

@hmottestad would be great if we can have a first 4.3.0 milestone release containing this change

**Closed by aschwarte10** 2023-02-20 08:16 UTC
Labels: 📶 enhancement
