### ISSUE TITLE
Eclipse RDF4j queries are not returning results for 2.3 or newer version

### ISSUE THREAD

**Issue by NarendraSadhu** [eclipse/rdf4j#2310] opened 2020-06-09 04:40 UTC
We are using an Rdf4j SPARQLRepository to access a remote Blazegraph server and query it. If we use rdf4j 2.2, this works as expected. However, if you use rdf4j 2.3 or newer, this does not work and queries are not returning result.

**Comment by jeenbroekstra** [comment] 2020-06-09 23:30
Can you provide more information about the circumstances: what version of Blazegraph are you using, and an example query and data set where the problem occurs, what does the exact configuration of your SPARQLRepository look like (endpoint urls, any authentication, etc).

**Comment by jeenbroekstra** [comment] 2020-06-09 23:31
Possible duplicate of #1393 (which was closed because we couldn't reproduce).

**Comment by NarendraSadhu** [comment] 2020-06-10 06:34
- We are facing issue while upgrading from RDF4J version 2.2 to version 2.3 or above
- Currently we are using local Blazegraph 2.1.4 version and SPARQLRepository connection to access it. Below are the configuration of SPARQLRepository and sample query to find objectcounter by projectId and variantId.

SPARQLRepository Configuration:

        @Bean
	public Repository getRepository() {
		// Blaze graph
		String sparqlEndpoint = "http://localhost:9999/blazegraph/sparql"
		return new SPARQLRepository(sparqlEndpoint);
	}

Sample Query:

prefix projects: <http://www.siemens.com/krawalcloud/projects/> 
SELECT DISTINCT ?objectCounter 
WHERE {?parent 	projects:hasUUID "ad0ee396-dcc5-4395-b23e-3c476cea3330"^^xsd:string ;
               	projects:hasVariant ?variant.
       ?variant projects:hasUUID "a3fea6fa-3f0b-4ef5-8e8e-b2a8397f435b"^^xsd:string ;
               	projects:hasObjectCounter  ?objectCounter.
      }

**Comment by jeenbroekstra** [comment] 2020-06-10 06:37
Can you show me what the result of this query is when you execute it _directly_ on blazegraph (instead of via the RDF4J SPARQLRepository)?

**Comment by NarendraSadhu** [comment] 2020-06-10 07:17
@jeenbroekstra Please find the attached image. Getting query result when we are executing in Blazegraph. But When we are executing via RDF4J SPARQLRepository with version 2.3 or newer getting empty result.
![Query Result](https://user-images.githubusercontent.com/66659935/84238347-89f01980-ab18-11ea-8f83-468873f92a5e.JPG)

**Comment by jeenbroekstra** [comment] 2020-06-10 07:33
Based on this information I can not reproduce the issue, unfortunately. On a locally running blazegraph (2.1.4) I added minimal data to match your query:

```
prefix projects: <http://www.siemens.com/krawalcloud/projects/>
INSERT DATA {
<urn:project1>	projects:hasUUID "ad0ee396-dcc5-4395-b23e-3c476cea3330"^^xsd:string ;
               	projects:hasVariant <urn:variant-1>.
       <urn:variant-1> projects:hasUUID "a3fea6fa-3f0b-4ef5-8e8e-b2a8397f435b"^^xsd:string ;
               	projects:hasObjectCounter 2.
}
```

Then running your sparql query via a SPARQLRepository (using RDF4J 3.2.1), I get back the expected result:

		Repository rep = new SPARQLRepository("http://localhost:10080/blazegraph/sparql");

		try (RepositoryConnection conn = rep.getConnection()) {
			String query = "prefix projects: <http://www.siemens.com/krawalcloud/projects/> \n" +
					"SELECT DISTINCT ?objectCounter \n" +
					"WHERE {?parent 	projects:hasUUID \"ad0ee396-dcc5-4395-b23e-3c476cea3330\"^^xsd:string ;\n" +
					"               	projects:hasVariant ?variant.\n" +
					"       ?variant projects:hasUUID \"a3fea6fa-3f0b-4ef5-8e8e-b2a8397f435b\"^^xsd:string ;\n" +
					"               	projects:hasObjectCounter  ?objectCounter.\n" +
					"      }";
			TupleQueryResult result = conn.prepareTupleQuery(query).evaluate();

			result.forEach(System.out::println);
		}

output:

     [objectCounter="2"^^<http://www.w3.org/2001/XMLSchema#integer>]

**Comment by jeenbroekstra** [comment] 2020-06-10 07:49
Could you try and run the following curl command: 

```
curl -v http://localhost:9999/blazegraph/sparql -d 'query=prefix projects: <http://www.siemens.com/krawalcloud/projects/>
SELECT DISTINCT ?objectCounter
WHERE {?parent  projects:hasUUID "ad0ee396-dcc5-4395-b23e-3c476cea3330"^^xsd:string ;
                projects:hasVariant ?variant.
       ?variant projects:hasUUID "a3fea6fa-3f0b-4ef5-8e8e-b2a8397f435b"^^xsd:string ;
                projects:hasObjectCounter  ?objectCounter.
      }'
```

and tell me the complete output you see?

When I run this locally, I get this:

```
*   Trying 127.0.0.1:9999...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9999 (#0)
> POST /blazegraph/sparql HTTP/1.1
> Host: localhost:9999
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Length: 387
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 387 out of 387 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/sparql-results+xml
< Transfer-Encoding: chunked
< Server: Jetty(9.3.9.v20160517)
<
<?xml version='1.0' encoding='UTF-8'?>
<sparql xmlns='http://www.w3.org/2005/sparql-results#'>
        <head>
                <variable name='objectCounter'/>
        </head>
        <results>
                <result>
                        <binding name='objectCounter'>
                                <literal datatype='http://www.w3.org/2001/XMLSchema#integer'>2</literal>
                        </binding>
                </result>
        </results>
</sparql>
* Connection #0 to host localhost left intact
```

**Comment by NarendraSadhu** [comment] 2020-06-10 09:52
we tried to execute above curl command . But getting below error

curl -v http://localhost:9999/blazegraph/sparql -d 'query=prefix projects: <http://www.siemens.com/krawalcloud/projects/> SELECT DISTINCT ?objectCounter WHERE {?parent  projects:hasUUID "ad0ee396-dcc5-4395-b23e-3c476cea3330"^^xsd:string ; projects:hasVariant ?variant. ?variant projects:hasUUID "a3fea6fa-3f0b-4ef5-8e8e-b2a8397f435b"^^xsd:string ; projects:hasObjectCounter  ?objectCounter.}'
The filename, directory name, or volume label syntax is incorrect.

If we are able to connect Blazegraph by using below command

curl -v http://localhost:9999/blazegraph/sparql
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9999 (#0)
> GET /blazegraph/sparql HTTP/1.1
> Host: localhost:9999
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/rdf+xml
< Transfer-Encoding: chunked
< Server: Jetty(9.2.z-SNAPSHOT)
<
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
        xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">

<rdf:Description rdf:nodeID="service">
        <rdf:type rdf:resource="http://www.w3.org/ns/sparql-service-description#Service"/>
        <endpoint xmlns="http://www.w3.org/ns/sparql-service-description#" 

.........

</rdf:RDF>* Connection #0 to host localhost left intact

**Comment by jeenbroekstra** [comment] 2020-06-10 10:30
Not sure why you're getting an error on that, but it have to do with newlines in the query. Can you try this instead:

     curl -v http://localhost:10080/blazegraph/sparql -d 'query=prefix projects: <http://www.siemens.com/krawalcloud/projects/> SELECT DISTINCT ?parent ?objectCounter WHERE {?parent     projects:hasUUID "ad0ee396-dcc5-4395-b23e-3c476cea3330"^^xsd:string ;                 projects:hasVariant ?variant.       ?variant projects:hasUUID "a3fea6fa-3f0b-4ef5-8e8e-b2a8397f435b"^^xsd:string ;                    projects:hasObjectCounter  ?objectCounter.      }'

It's really important that I see the full result of the actual SPARQL query as it gets sent in the response, because I want to determine if the problem is somehow caused by a syntax issue in your data (though it seems unlikely).

Alternatively, we will have to start looking at log files, in particular the logs of Blazegraph itself (incoming request, outgoing response when you do the query), and hopefully also what RDF4J receives.

**Comment by jeenbroekstra** [comment] 2020-06-10 10:31
If you have an option to share part of your dataset with me so that I can upload to blazegraph and try and reproduce that way, that would be great.

**Comment by jeenbroekstra** [comment] 2020-06-10 23:27
Finally, another thing to look at might be the Java code you use to execute the query and process the result.

**Comment by NarendraSadhu** [comment] 2020-06-12 06:40
@jeenbroekstra  we can't send the our project dataset. But we are using ModelBuilder class for insert data to Blazegraph. Please find below sample code.

            Repository rep = new SPARQLRepository("http://localhost:9999/blazegraph/sparql");
		rep.initialize();
		try (RepositoryConnection conn = rep.getConnection()) {
			ModelBuilder builder = new ModelBuilder();
			
			String projectUUID = "ad0ee396-dcc5-4395-b23e-3c476cea3330";
			String variantUUID = "a3fea6fa-3f0b-4ef5-8e8e-b2a8397f435b";
			
			String projectVariant = projectUUID + "/variants/" + variantUUID;

			builder.setNamespace("root", "http://www.siemens.com/krawalcloud/projects/").setNamespace(RDF.NS);

			builder.subject("http://www.siemens.com/krawalcloud/projects/" + projectUUID)
					.add("http://www.siemens.com/krawalcloud/projects/" + "hasUUID", projectUUID)
					.add("http://www.siemens.com/krawalcloud/projects/" + "hasVariant", conn.getValueFactory().createIRI(("http://www.siemens.com/krawalcloud/projects/" + projectVariant)));

			builder.subject("http://www.siemens.com/krawalcloud/projects/" + projectVariant)
					.add("http://www.siemens.com/krawalcloud/projects/" + "hasUUID", variantUUID)
					.add("http://www.siemens.com/krawalcloud/projects/" + "hasObjectCounter", 2);

			Model model = builder.build();
			conn.add(model);

We are not facing any issues while inserting data but when we try to fetch data getting result with version 2.2 and getting empty result with newer versions.

Could you try to insert data using ModelBuilder (2.2 version) and fetch the data with different versions.

**Comment by jeenbroekstra** [comment] 2020-06-12 08:00
I still can not reproduce. I get back a result from Blazegraph (2.1.4), as expected, whether I use RDF4J 2.2.1, 2.3.1, or 3.2.2. 

To move forward on this, some further questions and things to investigate: 

1. can you tell me how large your Blazegraph data base is, in terms of the number of statements? Ballpark figure. 
2. is it just this one query you have shown here that is not giving a result, or are _all_ queries suddenly not working?
3. have a look in the RDF4J and Blazegraph logs, see if anything suspicious turns up. If necessary, at the RDF4J end, configure logging to use DEBUG level to get more detailed information about what happens when it sends a query and receives a response. 
4. can you show exactly how you execute the query and process the result - that is the code used to open a connection, create the query, evaluate it, and then process the query result. 
5. try and run the curl command I gave you earlier . 

More generally: if there is any way in which you can create a complete, minimal, verifiable example (data + code + query) that demonstrates the problem in a way that we can reproduce, that would be really helpful.

**Comment by hmottestad** [comment] 2020-06-12 21:33
Just popping my head in here to 1+ the need for a reproducible example. At this point it’s pretty much the only way for us to find out what is going on.

**Comment by jeenbroekstra** [comment] 2020-06-24 07:54
I'm closing this for now as we cannot reproduce the problem. If you can provide further details, feel free to comment and we can re-open.

**Closed by jeenbroekstra** 2020-06-24 07:54 UTC
Labels: cannot reproduce
