### ISSUE TITLE
Possible deadlock when processing query results from an RDF4J server

### ISSUE THREAD

**Issue by ledsoft** [eclipse/rdf4j#2918] opened 2021-03-12 12:11 UTC
Hello all,
I've encountered a situation that feels like a bug in query result processing.

**The problem:** I have a select that I execute against a repository on an RDF4J server. When going through the results, a follow-up select query is run for each item. The problem is that RDF4J hangs when processing the follow-up query results. 

**Steps to reproduce:** Setup an RDF4J server, create a repository (type doesn't matter, no inference is needed). Load the [SKOS](https://www.w3.org/TR/skos-reference/skos.rdf) vocabulary as sample data. The following test (JUnit 5) hangs when attempting to get the `ranges`:

```java
public class DeadlockTest {

    private static final String REPO_URI = "http://localhost:8080/rdf4j-server/repositories/skos";

    private static final String MAIN_QUERY = "SELECT ?property WHERE { ?property a rdf:Property . }";

    private static final String SUB_QUERY = "SELECT ?range WHERE { ?property rdfs:range ?range . }";

    private Repository repository;

    @BeforeEach
    void setUp() {
        this.repository = RepositoryProvider.getRepository(REPO_URI);
    }

    @AfterEach
    void tearDown() {
        repository.shutDown();
    }

    @Test
    void testRDF4JQueryDeadlock() {
        final Map<URI, Set<URI>> propertyRanges = new HashMap<>();
        try (final RepositoryConnection conn = repository.getConnection()) {
            final TupleQuery main = conn.prepareTupleQuery(MAIN_QUERY);
            final TupleQueryResult mainResult = main.evaluate();
            while (mainResult.hasNext()) {
                final BindingSet current = mainResult.next();
                final URI u = URI.create(current.getValue("property").stringValue());
                // This works just fine
                assertTrue(conn.getStatements(conn.getValueFactory().createIRI(u.toString()), null, null).hasNext());
                final TupleQuery subQuery = conn.prepareTupleQuery(SUB_QUERY);
                subQuery.setBinding("property", conn.getValueFactory().createIRI(u.toString()));
                final TupleQueryResult sqResult = subQuery.evaluate();
                // This hangs indefinitely
                final Set<URI> ranges = sqResult.stream().map(bs -> URI.create(bs.getValue("range").stringValue())).collect(Collectors.toSet());
                propertyRanges.put(u, ranges);
            }
        }
        assertFalse(propertyRanges.isEmpty());
    }
}
```

**Additional notes:**
- Tried with multiple RDF4J API versions (including 3.6.1, 3.6.0 and 3.5.1), also (just to be sure) on JDK 8 a 11
- Tried with different servers (RDF4J, GraphDB), remote and local
- Tried creating a new `RepositoryConnection` instance for the follow-up query, no effect
- This issue does not affect embedded memory or native store. If I create them locally from the application, everything works just fine
- From the log, it seems to me the problem is with iterating over the second query results. The server returns results but the iteration gets stuck on synchronization (partial thread stack shown below)
```
java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	  at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:417)
	  at org.eclipse.rdf4j.common.iteration.QueueIteration.getNextElement(QueueIteration.java:127)
	  at org.eclipse.rdf4j.common.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:81)
	  at org.eclipse.rdf4j.common.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:49)
	  at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
	  at org.eclipse.rdf4j.common.iteration.IterationSpliterator.forEachRemaining(IterationSpliterator.java:72)
	  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	  at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	  at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	  at cz.cvut.kbss.jopa.test.query.sesame.DeadlockTest.testRDF4JQueryDeadlock(DeadlockTest.java:58)
	...
```
If any more information is needed, please, let me know. If this is a false alarm, I apologize.

Thanks,
Martin

**Comment by kenwenzel** [comment] 2021-03-12 18:10
Maybe `sqResult` has to be closed in each iteration?

**Comment by ledsoft** [comment] 2021-03-12 20:45
Thanks for the reply, Ken, but no, that doesn't help and the `sqResult` is closed automatically by the stream spliterator.

**Comment by hmottestad** [comment] 2021-03-12 20:48
The issue is likely, as you point out, that you are not closing your resources. Query results need to be closed as well as the result of getStatements(...).

**Comment by ledsoft** [comment] 2021-03-12 20:48
And actually the processing gets stuck in the first iteration of the `while` loop, so it never gets to closing the `sqResult` anyway.

**Comment by ledsoft** [comment] 2021-03-12 20:51
The `getStatements` call was there just to illustrate that the repository itself is still responsive. If I remove it, the test still gets stuck.

**Comment by ledsoft** [comment] 2021-03-12 20:54
Here's code which I believe to be correct w.r.t. to closing resources. It behaves the same as the original example, i.e., get's stuck when processing the results of the sub-query.
```java
    @Test
    void testRDF4JQueryDeadlock() {
        final Map<URI, Set<URI>> propertyRanges = new HashMap<>();
        try (final RepositoryConnection conn = repository.getConnection()) {
            final TupleQuery main = conn.prepareTupleQuery(MAIN_QUERY);
            try (TupleQueryResult mainResult = main.evaluate()) {
                while (mainResult.hasNext()) {
                    final BindingSet current = mainResult.next();
                    final URI u = URI.create(current.getValue("property").stringValue());
                    final TupleQuery subQuery = conn.prepareTupleQuery(SUB_QUERY);
                    subQuery.setBinding("property", conn.getValueFactory().createIRI(u.toString()));
                    final TupleQueryResult sqResult = subQuery.evaluate();
                    // This hangs indefinitely
                    final Set<URI> ranges = sqResult.stream().map(bs -> URI.create(bs.getValue("range").stringValue())).collect(Collectors.toSet());
                    propertyRanges.put(u, ranges);
                }
            }
        }
        assertFalse(propertyRanges.isEmpty());
    }
```

**Comment by jeenbroekstra** [comment] 2021-03-15 23:30
I've reproduced this, appears to be a bug. It is specific to SPARQL query processing (the equivalent getStatements API does not have the problem), but not specific to Stream-based processing (the happens when using for-each on the `sqResult`). Also confirmed that not closing `sqResult` is not the cause.

**Comment by jeenbroekstra** [comment] 2021-03-15 23:50
The problem appears to be client-side, somewhere in the code for the BackgroundTupleQueryresult.

**Comment by jeenbroekstra** [comment] 2021-03-16 00:31
Cause is that the ScheduledExecutorService used for processing background query results is by default initialized with a thread pool size of 1. The main query occupies the existing thread while the result is being processed. This blocks the subquery from getting its result processed (because the executor has no free thread and apparently also is not triggered to create a new thread).

I am not entirely sure _why_ the executor service doesn't just spawn a new thread - the core pool size is not a fixed limit, it should just be the minimum number of live threads, but should not block it from creating more. Either we are using the ScheduledExecutorService wrong or there is some subtle edge-case bug in its thread spawn logic. 

A temporary workaround: set the `org.eclipse.rdf4j.client.executors.corePoolSize` system property to 2 or higher (see https://rdf4j.org/documentation/programming/repository/#configuring-the-http-session-thread-pool) .

**Comment by jeenbroekstra** [comment] 2021-03-16 01:49
I think a good fix would be to set our default core pool size higher, to, say, 4 or so. It will not actually spin up these core threads until they're needed so the resource impact is minimal, but it would stop interdependent query requests from being queued, in other words deadlocked. Optionally we can also configure the thread pool executor to terminate core threads when idle for a certain amount of time.

**Comment by ledsoft** [comment] 2021-03-16 07:41
Thanks, Jeen!

**Closed** 2021-03-17 05:05 UTC
Labels: 🐞 bug
