### ISSUE TITLE
DESCRIBE produces duplicate statements

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#530] opened 2016-09-07 00:24 UTC
(Migrated from https://openrdf.atlassian.net/browse/SES-723)

If the database contains the statement [ ex:a ex:p ex:a ] then the query "DESCRIBE ex:a" returns [ ex:a ex:p ex:a ] twice.

**Comment by pulquero** [comment] 2016-09-10 22:05
From the spec, "The DESCRIBE form returns a single result RDF graph containing RDF data about resources." CONSTRUCT produces an RDF graph too and doesn't dedup, so if I understand the issue correctly, this should be a "not a bug/wont fix" for the same reasons CONSTRUCT doesn't dedup.

**Comment by ansell** [comment] 2016-09-11 23:25
I don't think either the SPARQL or RDF Abstract Model specs specify whether concrete RDF documents should/shall/etc. be deduplicated. The RDF Abstract Model specifies that in abstract terms the final model is a Set, which implies deduplication has occurred at that point, but it doesn't say anything about parsing methods or concrete formats.

**Closed** 2016-10-23 22:58 UTC
Labels: wontfix
