### ISSUE TITLE
Docker container does not work on other port than 8080

### ISSUE THREAD

**Issue by ilytra** [eclipse/rdf4j#2336] opened 2020-06-25 08:05 UTC
When following this https://hub.docker.com/r/eclipse/rdf4j-workbench to create a new container on a different port, e.g.:
`docker run -d -p 8088:8080 -e JAVA_OPTS="-Xms1g -Xmx4g"     -v data:/var/rdf4j -v logs:/usr/local/tomcat/logs eclipse/rdf4j-workbench:amd64-latest`

![Screenshot from 2020-06-25 09-17-08](https://user-images.githubusercontent.com/463055/85681117-432f2180-b6cb-11ea-99fb-cf839c16144f.png)
going to  http://localhost:8088/rdf4j-workbench an exception occurs and no new repositories can be added.
Attached is what you see on the frontend, here is the exception:
```
25-Jun-2020 06:52:03.910 WARNING [http-nio-8080-exec-1] org.eclipse.rdf4j.workbench.proxy.ServerValidator.checkServerPrefixes server URL null does not have a prefix file: http: https:
25-Jun-2020 06:52:03.911 WARNING [http-nio-8080-exec-1] org.eclipse.rdf4j.workbench.proxy.ServerValidator.canConnect java.net.ConnectException: Connection refused (Connection refused)
 java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.URL.openStream(URL.java:1045)
	at org.eclipse.rdf4j.workbench.proxy.ServerValidator.canConnect(ServerValidator.java:104)
	at org.eclipse.rdf4j.workbench.proxy.ServerValidator.isValidServer(ServerValidator.java:64)
	at org.eclipse.rdf4j.workbench.proxy.WorkbenchGateway.findWorkbenchServlet(WorkbenchGateway.java:229)
	at org.eclipse.rdf4j.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:105)
	at org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.eclipse.rdf4j.workbench.proxy.CacheFilter.doFilter(CacheFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.eclipse.rdf4j.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by barthanssens** [comment] 2020-06-25 08:11
Hi

could this be a typo ? I've noticed the example uses --p 80**88**:8080 for Docker, while trying to connect to 80**89**

**Comment by ilytra** [comment] 2020-06-25 09:49
No, it is not a typo, I tried with different ports, to see if it makes a difference and maybe I copy-pasted different ports. With 8080 it works fine. Can this be a problem with the hardcoded values in docker-compose https://github.com/eclipse/rdf4j/blob/d2a301dabcf9c051b019e3434327c15c29fc321e/assembly/src/main/dist/docker/docker-compose.yml ?

**Comment by barthanssens** [comment] 2020-06-25 13:45
Hmz, strange, so I have to dig into this a little deeper to see if I can reproduce the problem...

On my system, I'm running amd64-latest on port 8089 and it seems to work:
- not using docker-compose, just `docker run -p 8089:8080 ...`
- the rdf4j-server remains unchanged, i.e. http://localhost:8080/rdf4j-server
- creating a memory store or native store via the webinterface (with defaults) seems to work just fine

**Comment by hmottestad** [comment] 2020-07-19 15:26
@barthanssens were you able to reproduce this or should we close this issue?

**Comment by barthanssens** [comment] 2020-07-19 18:52
Not yet, I'd suggest to add a "could not reproduce", but perhaps leave it open for a bit longer (hoping some extra info may help).

**Comment by mielvds** [comment] 2021-07-20 10:03
I run into the same issue on a M1 macbook pro with Big Sur 11.4 running the `arm64v8-latest` build. The interface loads, but I can't use any of the functions (eg. clicking create repository does nothing)  @ilytra what system are you trying this on?

**Comment by barthanssens** [comment] 2021-07-21 21:30
Hmz, thanks for the heads-up, I have to look into it...

**Closed** 2021-11-27 01:13 UTC
Labels: 📦 workbench, cannot reproduce
