### ISSUE TITLE
StrictEvaluationStrategy passes an invalid context array for sparql query

### ISSUE THREAD

**Issue by hbasejanitor** [eclipse/rdf4j#702] opened 2016-12-28 03:41 UTC
Hi,

When StrictEvaluationStrategy parses this query:

PREFIX schema:  <http://schema.org/> select ?foo from default where {?foo schema:inLanguage ?bar .}

The context array is passing an array of size one with null as the value, it's causing the sparql query to the memorystoreconnection to fail.

**Comment by hbasejanitor** [comment] 2016-12-28 03:42
This is the block causing the issue:

				else {
					contexts = new Resource[graphs.size()];
					int i = 0;
					for (IRI graph : graphs) {
						IRI context = null;
						if (!SESAME.NIL.equals(graph)) {
							context = graph;
						}
						contexts[i++] = context;
					}
				}
(in StrictEvaluationStrategy )

**Comment by jeenbroekstra** [comment] 2017-01-09 06:22
That keyword 'default' should probably be removed from the parser. It's an undocumented feature. 

But that might not be something we can do as a quick patch. The immediate fix would be to make sure it gets converted to a `SESAME.NIL` value when passed into the context array.

**Comment by jeenbroekstra** [comment] 2017-01-09 06:24
Relevant discussion about 'sesame:nil' vs. 'default': https://openrdf.atlassian.net/browse/SES-850

**Comment by jeenbroekstra** [comment] 2017-01-18 00:01
Ok my previous comments were pretty much on autopilot. I just tried to reproduce any problem with this and it seems to operate fine. 

> the context array is passing an array of size one with null as the value,

That is by design - it the way to explicitly query for statements _without_ context.

**Comment by jeenbroekstra** [comment] 2017-01-18 01:14
I'm closing this since I think it's a misunderstanding of how the context mechanism works, rather than a bug. If I've overlooked something, let me know.

**Closed by jeenbroekstra** 2017-01-18 01:14 UTC
Labels: wontfix
