### ISSUE TITLE
Sorting values with datatype - performance

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2442] opened 2020-08-16 15:17 UTC
Values with datatype are slow to sort because there is effectively a lot of string equals to determine which datatype is being used. 

We should look at what options we have to reduce the amount of string equals operations. Maybe some sort of interning, or a new class with helper methods, or enums?

**Comment by hmottestad** [comment] 2020-08-16 17:14
Step one would be to profile sorting of various values to show that comparing data types is the issue.

**Comment by jeenbroekstra** [comment] 2020-08-16 23:18
Can you give some context? Are you talking about SPARQL ordering, or one of our comparator utilities, or both? A particular triplestore, or more generally?

**Comment by hmottestad** [comment] 2020-08-17 10:08
<img width="1680" alt="Screenshot 2020-08-17 at 12 08 41" src="https://user-images.githubusercontent.com/797185/90384784-67cbc800-e082-11ea-8b5f-4d2e3db3dfda.png">

**Comment by hmottestad** [comment] 2020-08-17 10:10
I created a simple test to show that SimpleIRI.equals is the method that takes the most time during sorting. Mostly from determining the datatype. This is with the ValueComparator.

**Comment by hmottestad** [comment] 2020-08-17 10:55
<img width="1529" alt="Screenshot 2020-08-17 at 12 50 17" src="https://user-images.githubusercontent.com/797185/90388539-3f46cc80-e088-11ea-88ad-ca97e572411d.png">

Here is part of the flame graph showing just the comparisons. 

Take away from this is that `compareLiterals(...)` uses most of its time trying to determine the datatype. Which it needs to do many times for the same value when sorting. There is also the ´nullEquals(...)` method which I think is unneeded. I'll look into that.

**Comment by hmottestad** [comment] 2020-08-17 10:59
Made a little PR with my code: https://github.com/eclipse/rdf4j/pull/2447

**Comment by hmottestad** [comment] 2020-08-19 21:26
The merged PR only solves part of this issue. We still have the issue of the large amount of time being used to determine the datatype of literals.

**Comment by jeenbroekstra** [comment] 2020-08-19 22:37
> The merged PR only solves part of this issue. We still have the issue of the large amount of time being used to determine the datatype of literals.

Just from looking at the code in XMLDatatypeUtil: we're doing a lot of `uri.equals(XSD.DT1) || uri.equals(XSD.D2) || ...`. to check if a datatype is numerical, or a calendar type, etc. I wonder if a simple optimization would be to stick those types in a fixed collection and do a `collection.contains(uri)`. If we use something like a LinkedHashSet this would gives us a better average lookup performance.

**Comment by jeenbroekstra** [comment] 2020-08-20 01:33
I am taking a closer look at the benchmark you wrote. What exactly are you benchmarking? There's talk of pointers, and a "deepEquals", and you seem to be testing subjects, predicates, and objects. I mean I can run the thing and get numbers out, but I don't understand what I'm looking at.

**Comment by jeenbroekstra** [comment] 2020-08-20 01:39
I've opened a new branch for this issue, with (initially) a minor modification in the setup, to ensure we can run the benchmark from the command line. I'm going to try and see if the idea I have for the XMLDatatypeUtil is useful. Happy to collaborate on that branch as well, feel free to push your updates there.

**Comment by hmottestad** [comment] 2020-08-20 06:58
Your branch looks great. 

I've also been playing around with the idea of introducing new methods on literals, like isNumber, isInteger, isCalendar. And have an enum for the known datatype a internally that gets populated on instantiation. Do you think that would be a good idea?

**Comment by jeenbroekstra** [comment] 2020-08-20 11:35
I'm not sure. I'm wary of adding additional public methods to the core value classes, and not quite sure I follow what you have in mind. In any case perhaps pick it up in a follow up issue so we can keep it separate from these quick fixes.

**Comment by hmottestad** [comment] 2020-08-20 21:50
This was supposed to be the broader issue where we could discuss and implement various improvements. I was kinda hoping to keep it around instead of making more issues. 

I know it’s not always a good idea to make more public methods, but I feel that the sorting of literals is so needlessly slow due to us for every comparison having to refer to the strings inside IRIs in order to determine the datatype. Your use of hashmaps makes it faster, but I think we could easily make it 2x faster by using an enum for all the known xsd datatypes.

**Comment by jeenbroekstra** [comment] 2020-08-21 00:44
> This was supposed to be the broader issue where we could discuss and implement various improvements. I was kinda hoping to keep it around instead of making more issues.

I see. I changed this ticket to a bug fix ticket when you put up a PR with, well, a bug fix.  A release with that PR (and mine as well) is imminent. But fair enough, we'll deschedule this ticket for now and keep it open for the broader discussion. It does mean that we won't really be able to refer to the fixes already done in the release notes, but I can live with that for this instance.

I'm absolutely fine with having these broader "design discussion / epic" tickets by the way, they're useful. However, for keeping track of what gets fixed where, it's important that PRs  that address only _part_ of the problem should get their own, specific, subtask issues (and the PR should be logged against that subtask, rather than the epic issue). We can continue on this ticket for now as you prefer, since it's already a bit messy. In future, however, the principle should always be that any fix that gets merged is self-contained and completely fixes the issue to which it refers (barring unforeseen regressions and followups of course). 

As an aside I just found a github action that we could use to (semi-)automatically keep track of epics and their subtasks. I'll take a closer look at it and set something up to make this all a bit easier.

> I know it’s not always a good idea to make more public methods, but I feel that the sorting of literals is so needlessly slow due to us for every comparison having to refer to the strings inside IRIs in order to determine the datatype. Your use of hashmaps makes it faster, but I think we could easily make it 2x faster by using an enum for all the known xsd datatypes.

First fo all: I can see there are performance improvements possible, but what concrete end user problem are we attempting to solve here? Are you experiencing a bottleneck in a particular project you're doing? If so, how are you using RDF4J in that project to make this problem high priority? I'm fine with doing quick internal fixes that clearly improve performance, but if we change the design of the API significantly then I think we need a more concrete justification / use case than just a low-level "sorting should be faster". 

As to 'referring to the strings inside IRIs', I think you're overestimating how often that happens, especially with the changes we now made. The xsd datatype constant objects are consistently reused throughout the project for creating typed literals, so typically object reference equality will be the only check needed for comparison.

All that being said I'm not against discussing and testing an improved design of course. I just want to make sure we have our rationale straight before diving into the rabbit hole. Can you sketch in some pseudo-code what you roughly have in mind, and how you think it will help performance?

**Comment by jeenbroekstra** [comment] 2020-08-21 03:59
This was automatically closed because I merged the associated PR. Re-opening to continue discussion (another good demonstration why I prefer a 1:1 relation between a ticket and a PR, btw).

**Comment by hmottestad** [comment] 2020-08-21 07:11
This isn't high priority. It's based on some work I did last year trying to improve the SHACL performance by testing out various sorted memory structures and discovered that OSPC was considerably slower than SPOC. I then discovered that we were spending a lot of time during sorting just determining the datatype. 

I'll rerun the profiling to see how much time is used now to determine the datatype. 

Making RDF4J faster, especially for something as fundamental as sorting is always worthwhile. This goes to the roots of my experience with semantic tech where there has been a lot of negativity connected to semantic tech being slow.

**Comment by jeenbroekstra** [comment] 2020-08-23 21:00
But that's already the case now. What problem are you solving in the current code? Where are you seeing these string comparisons happening?

**Comment by jeenbroekstra** [comment] 2020-08-23 22:11
Another point to keep in mind: instantiating literals is the job of the ValueFactory. Can we do something clever internally there to fix the issue instead?

**Comment by hmottestad** [comment] 2020-08-24 04:56
<img width="1290" alt="Screenshot 2020-08-24 at 06 55 33" src="https://user-images.githubusercontent.com/797185/91005350-f7b7c780-e5d6-11ea-8d5a-9c413c73e23f.png">

**Comment by hmottestad** [comment] 2020-08-24 04:59
When comparing literals, we are still only using ~7.5% of the time actually comparing literals.

**Comment by hmottestad** [comment] 2020-08-24 08:25
<img width="1413" alt="Screenshot 2020-08-24 at 10 20 43" src="https://user-images.githubusercontent.com/797185/91021117-97834e80-e5f3-11ea-89c4-5b5743839584.png">

Added interning of the IRI string. This helps quite a lot, but it's still pretty bad. As you can see we are not spending ~12% of the time on the actual literal comparison, which means we are spending less time on other things. I think String interning for all IRIs might be a bit overkill and the performance benefits don't outweigh it here.

**Comment by hmottestad** [comment] 2020-08-24 08:26
My idea about introducing an enum for known datatypes might also make user code faster, if they adopt it that is.

**Comment by jeenbroekstra** [comment] 2020-08-24 08:57
> When comparing literals, we are still only using ~7.5% of the time actually comparing literals.

That 7.5% you're looking at is the `QueryEvaluationUtil.compareLiterals` method, which is only called from the ValueComparator if you are comparing two plain (non-datatyped) literals. If your input literals are datatyped, the code path quite naturally goes into the `compareDatatypes` method. So unless I misunderstand how you're measuring this, that method taking up the bulk of your time is not a reflection of its inefficiency, but merely caused by the fact that your input literals are almost all datatyped.

**Comment by jeenbroekstra** [comment] 2020-08-24 09:03
Actually that's not quite right either. Hm, the logic in ValueComparator is a little convoluted.

**Comment by jeenbroekstra** [comment] 2020-08-24 09:12
Ok, look, let's spike the idea, see if it actually does give us a real performance boost (the flame graph doesn't tell us much in that respect), and then we can look at it further to see how to best fit it into the framework.

**Closed** 2020-11-15 11:29 UTC
Labels: ⏩ performance, 💬 needs discussion, 📶 enhancement
